"""Auto-generated by fcstd2b123d from tests/fixtures/tier3_corpus/ANSI-ASME-B18_2_1_Hex_Head_Cap_Screw_1_4-20x1.FCStd."""

from build123d import Axis, Circle, Line, Plane, chamfer, extrude, make_face, revolve


def _edges_at(shape, points, tol=1e-3):
    """Select edges whose midpoints match any of the target points.

    Used by translated Fillet / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 7 lines (1 loops)
Sketch = Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(
        Line((0, 4.7752), (5.55625, 4.7752))
        + Line((5.55625, 4.7752), (6.4158, 4.37438489602))
        + Line((6.4158, 4.37438489602), (6.4158, 0))
        + Line((6.4158, 0), (3.175, 0))
        + Line((3.175, 0), (3.175, -25.4))
        + Line((3.175, -25.4), (0, -25.4))
        + Line((0, -25.4), (0, 4.7752))
    )
)

# PartDesign::Revolution 'Revolution': angle=360.0
Revolution = revolve(Sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Hexagon': 7 lines, 1 circle (2 loops)
Sketch001 = Plane(
    origin=(0, 0, 4.775200000000002), x_dir=(-1, 0, 0), z_dir=(0, 0, 1)
) * (
    Circle(7.41580486637)
    - make_face(
        Line((-3.207902433185, 5.55625), (3.207902433185, 5.55625))
        + Line((3.207902433185, 5.55625), (6.41580486637, 0))
        + Line((6.41580486637, 0), (3.207902433185, -5.55625))
        + Line((3.207902433185, -5.55625), (-3.207902433185, -5.55625))
        + Line((-3.207902433185, -5.55625), (-6.41580486637, 0))
        + Line((-6.41580486637, 0), (-3.207902433185, 5.55625))
    )
)

# PartDesign::Pocket 'Pocket' (body-less, ThroughAll)
Pocket = Revolution - extrude(Sketch001, amount=-1000000.0)

# PartDesign::Chamfer 'Chamfer': size=1.0 on 1 edges of Pocket
Chamfer = chamfer(
    _edges_at(Pocket, [(-3.1750000000000007, 0, -25.400000000000006)]), length=1
)

result = Chamfer
