"""Auto-generated by fcstd2b123d from tests/fixtures/tier3_corpus/ANSI-ASME-B18_2_1_Hex_Head_Cap_Screw_1_4-20x1.FCStd."""

from build123d import (
    Axis,
    Circle,
    Edge,
    Plane,
    Polyline,
    Sketch,
    chamfer,
    extrude,
    make_face,
    revolve,
)
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated Fillet / chamfer_0 features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 7 lines (1 loops)
sketch_profile = Polyline(
    (0, 4.7752),
    (5.55625, 4.7752),
    (6.4158, 4.37438489602),
    (6.4158, 0),
    (3.175, 0),
    (3.175, -25.4),
    (0, -25.4),
    (0, 4.7752),
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_profile)
)

# PartDesign::Revolution 'Revolution': angle=360.0
revolution = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Hexagon': 7 lines, 1 circle (2 loops)
sketch_001_profile = Polyline(
    (-3.207902433185, 5.55625),
    (3.207902433185, 5.55625),
    (6.41580486637, 0),
    (3.207902433185, -5.55625),
    (-3.207902433185, -5.55625),
    (-6.41580486637, 0),
    (-3.207902433185, 5.55625),
)
sketch_001 = Sketch() + Plane(
    origin=(0, 0, 4.775200000000002), x_dir=(-1, 0, 0), z_dir=(0, 0, 1)
) * (Circle(7.41580486637) - make_face(sketch_001_profile))

# PartDesign::Pocket 'Pocket' (body-less, ThroughAll)
pocket = revolution - extrude(sketch_001, amount=-1000000.0)

# PartDesign::Chamfer 'Chamfer': size=1.0 on 1 edges of Pocket
chamfer_0 = chamfer(
    _edges_at(pocket, [(-3.1750000000000007, 0, -25.400000000000006)]), length=1
)

result = chamfer_0
