"""Auto-generated by fcstd2b123d from /Users/paul/Downloads/hinge-03.fcstd."""

from build123d import (
    Align,
    Axis,
    BasePartObject,
    CenterArc,
    Circle,
    Line,
    Mode,
    Plane,
    Polyline,
    RotationLike,
    Sketch,
    extrude,
    make_face,
    revolve,
)


class Hinge03(BasePartObject):
    """Translated parametric design. Defaults match the source values."""

    def __init__(
        self,
        hingeHeight: float = 40,
        pivotClearance: float = 1,
        pivotOuter: float = 10,
        rotation: RotationLike = (0, 0, 0),
        align: Align | tuple[Align, Align, Align] | None = None,
        mode: Mode = Mode.ADD,
    ):
        # Sketcher::SketchObject 'Sketch': 3 lines, 1 arc, 1 circle (2 loops)
        sketch_profile = Polyline((5, 0), (30, 0), (30, -5), (0, -5)) + CenterArc(
            center=(0, 0), radius=5, start_angle=270, arc_size=-270
        )
        sketch = Sketch() + Plane.XZ * (make_face(sketch_profile) - Circle(2.5))

        # PartDesign::Pad 'Pad': length=hingeHeight
        pad = extrude(sketch, amount=hingeHeight)

        # Sketcher::SketchObject 'Sketch002': 18 lines (1 loops)
        sketch_002_profile = Polyline(
            (-24, 23.433333333333348),
            (-24, -23.43333333333334),
            (6, -23.43333333333334),
            (6, -16.56666666666667),
            (-6, -16.56666666666667),
            (-6, -10.1),
            (6, -10.1),
            (6, -3.2333333333333334),
            (-6, -3.2333333333333334),
            (-6, 3.2333333333333334),
            (6, 3.2333333333333334),
            (6, 10.1),
            (-6, 10.1),
            (-6, 16.566666666666674),
            (6, 16.566666666666674),
            (6, 23.433333333333348),
            (-24, 23.433333333333348),
        )
        sketch_002 = make_face(sketch_002_profile)

        # PartDesign::Pocket 'Pocket': length=pivotOuter + pivotClearance
        pocket = pad - extrude(sketch_002, amount=-(pivotOuter + pivotClearance))

        # Sketcher::SketchObject 'Sketch001': 3 lines, 1 arc (1 loops)
        sketch_001_profile = Polyline(
            (-5, 0), (-30, 0), (-30, -5), (0, -5)
        ) + CenterArc(center=(0, 0), radius=5, start_angle=270, arc_size=270)
        sketch_001 = Sketch() + Plane.XZ * make_face(sketch_001_profile)

        # PartDesign::Pad 'Pad001': length=hingeHeight
        pad_001 = extrude(sketch_001, amount=hingeHeight)

        # Sketcher::SketchObject 'Sketch003': 14 lines (1 loops)
        sketch_003_profile = Polyline(
            (-6, -16.66666666666615),
            (34, -16.66666666666615),
            (34, 16.666666666666668),
            (-6, 16.666666666666668),
            (-6, 10),
            (6, 10),
            (6, 3.333333333333334),
            (-6, 3.333333333333334),
            (-6, -3.333333333333334),
            (6, -3.333333333333334),
            (6, -10),
            (-6, -10),
            (-6, -16.66666666666615),
        )
        sketch_003 = make_face(sketch_003_profile)

        # PartDesign::Pocket 'Pocket001': length=pivotOuter + pivotClearance
        pocket_001 = pad_001 - extrude(
            sketch_003, amount=-(pivotOuter + pivotClearance)
        )

        # Sketcher::SketchObject 'Sketch004': 12 lines, 6 arcs (4 loops)
        sketch_004_loop_0 = (
            Line((2, 10.75), (2, 2.583333333333325))
            + CenterArc(
                center=(0, 2.583333333333327), radius=2, start_angle=360, arc_size=-90
            )
            + Line((0, 0.5833333333333268), (0, 12.75))
            + CenterArc(center=(0, 10.75), radius=2, start_angle=90, arc_size=-90)
        )
        sketch_004_loop_1 = (
            Polyline(
                (0, 18.388888888888886), (2, 18.388888888888886), (2, 16.16666666666666)
            )
            + CenterArc(
                center=(0, 16.16666666666666), radius=2, start_angle=0, arc_size=-90
            )
            + Line((0, 14.16666666666666), (0, 18.388888888888886))
        )
        sketch_004_loop_2 = (
            CenterArc(
                center=(0, -2.5833333333401507), radius=2, start_angle=0, arc_size=90
            )
            + Line((0, -0.5833333333401516), (0, -12.75))
            + CenterArc(center=(0, -10.75), radius=2, start_angle=270, arc_size=90)
            + Line((2, -10.75), (2, -2.5833333333401516))
        )
        sketch_004_loop_3 = CenterArc(
            center=(0, -16.16666666665316), radius=2, start_angle=0, arc_size=90
        ) + Polyline(
            (0, -14.16666666665316),
            (0, -18.388888888888886),
            (2, -18.388888888888886),
            (2, -16.16666666665316),
        )
        sketch_004 = (
            make_face(sketch_004_loop_0)
            + make_face(sketch_004_loop_1)
            + make_face(sketch_004_loop_2)
            + make_face(sketch_004_loop_3)
        )

        # PartDesign::Revolution 'Revolution': angle=-360.0 (reversed)
        revolution = pocket_001 + revolve(sketch_004, axis=Axis.Y, revolution_arc=-360)

        super().__init__(
            part=revolution,
            rotation=rotation,
            align=align,
            mode=mode,
        )


result = Hinge03()
