"""Auto-generated by fcstd2b123d from tests/fixtures/tier2_partdesign/partdesign_example.FCStd."""

from build123d import CenterArc, Circle, Line, Plane, Pos, extrude, make_face

# Sketcher::SketchObject 'Sketch': 3 lines, 1 arc (1 loops)
Sketch = make_face(
    Line((20.358962517357057, 20), (-55, 20))
    + Line((-55, 20), (-55, -20))
    + Line((-55, -20), (55, -20))
    + CenterArc(
        center=(54.999978668734606, 15),
        radius=35,
        start_angle=270.00003491975656,
        arc_size=261.7867543785052,
    )
)

# PartDesign::Pad 'Pad': length=100.0 (reversed)
Pad = extrude(Sketch, amount=-100)

# Sketcher::SketchObject 'Sketch001': 4 lines (1 loops)
Sketch001 = make_face(
    Line((-45, 10), (55, 10))
    + Line((55, 10), (55, -10))
    + Line((55, -10), (-45, -10))
    + Line((-45, -10), (-45, 10))
)

# Sketcher::SketchObject 'Sketch002': 12 lines (1 loops)
Sketch002 = Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(
        Line((40, 20), (-40, 20))
        + Line((-40, 20), (-40, -10))
        + Line((-40, -10), (-24, -10))
        + Line((-24, -10), (-24, 10))
        + Line((-24, 10), (-8, 10))
        + Line((-8, 10), (-8, -10))
        + Line((-8, -10), (8, -10))
        + Line((8, -10), (8, 10))
        + Line((8, 10), (24, 10))
        + Line((24, 10), (24, -10))
        + Line((24, -10), (40, -10))
        + Line((40, -10), (40, 20))
    )
)

# Sketcher::SketchObject 'Sketch003': 1 circle (1 loops)
Sketch003 = Pos(54.999978668734606, 15) * Circle(25)

# PartDesign::Pocket 'Pocket': length=15.0
Pocket = Pad - extrude(Sketch001, amount=-15)

# PartDesign::Pocket 'Pocket001': length=50.0
Pocket001 = Pocket - extrude(Sketch003, amount=-50)

# PartDesign::Pocket 'Pocket002': ThroughAll (reversed)
Pocket002 = Pocket001 - extrude(Sketch002, amount=1000000)

result = Pocket002
