"""Auto-generated by fcstd2b123d from tests/fixtures/tier2_partdesign/partdesign_example.FCStd."""

from build123d import CenterArc, Circle, Plane, Polyline, Pos, extrude, make_face

# Sketcher::SketchObject 'Sketch': 3 lines, 1 arc (1 loops)
sketch_profile = Polyline(
    (20.358962517357057, 20), (-55, 20), (-55, -20), (55, -20)
) + CenterArc(
    center=(54.999978668734606, 15),
    radius=35,
    start_angle=270.00003491975656,
    arc_size=261.7867543785052,
)
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=100.0 (reversed)
pad = extrude(sketch, amount=-100)

# Sketcher::SketchObject 'Sketch001': 4 lines (1 loops)
sketch_001_profile = Polyline((-45, 10), (55, 10), (55, -10), (-45, -10), (-45, 10))
sketch_001 = make_face(sketch_001_profile)

# Sketcher::SketchObject 'Sketch002': 12 lines (1 loops)
sketch_002_profile = Polyline(
    (40, 20),
    (-40, 20),
    (-40, -10),
    (-24, -10),
    (-24, 10),
    (-8, 10),
    (-8, -10),
    (8, -10),
    (8, 10),
    (24, 10),
    (24, -10),
    (40, -10),
    (40, 20),
)
sketch_002 = Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_002_profile)
)

# Sketcher::SketchObject 'Sketch003': 1 circle (1 loops)
sketch_003 = Pos(54.999978668734606, 15) * Circle(25)

# PartDesign::Pocket 'Pocket': length=15.0
pocket = pad - extrude(sketch_001, amount=-15)

# PartDesign::Pocket 'Pocket001': length=50.0
pocket_001 = pocket - extrude(sketch_003, amount=-50)

# PartDesign::Pocket 'Pocket002': ThroughAll (reversed)
pocket_002 = pocket_001 - extrude(sketch_002, amount=1000000)

result = pocket_002
