"""Emit-source assertion tests — verify the *shape* of generated code,
not just that the resulting geometry is correct.

The corpus suite proves geometry equivalence; these tests prove the
emit is *good code*. They surface the open code-quality issues
(#43, #75, #76, #77, #78) as concrete failing assertions, so closing
those issues means removing the ``xfail`` marker — the test then
becomes a regression gate.

`xfail(strict=True)` is intentional: when the feature lands, the test
*passing* becomes a hard failure that forces the implementer to remove
the marker. That keeps the test honest and prevents "feature shipped
but the gate test still has xfail" drift.

Tests in this file are deliberately gated on the same FreeCAD-runtime
flag as `test_translator_tier1`; they exec the translator subprocess
and inspect its stdout.
"""

from __future__ import annotations

import pytest

from tests.test_translator_tier1 import _translate


# ---------------------------------------------------------------------------
# #75 — uniform patterns should emit `with PolarLocations` / `GridLocations`
# ---------------------------------------------------------------------------


def test_polar_pattern_uses_polar_locations() -> None:
    """A 6-fold uniform polar pattern should emit ONE ``PolarLocations(``
    term (algebra-mode multiplier), not six chained ``Rot(Z=k·60) * ...``
    terms.

    Algebra-mode emit uses ``base - PolarLocations(0, n, ...) * prism``;
    builder-mode emit (#78, future) would use ``with PolarLocations(...):``.
    Either is acceptable.
    """
    source = _translate("tests/fixtures/tier4_patterns/polar_pattern_holes.FCStd")
    assert "PolarLocations(" in source, (
        "expected a PolarLocations(...) term; emit still spells out copies"
    )
    # And no spelled-out Rot(Z=k) chain should remain for this single-Original
    # uniform pattern.
    rot_z_lines = sum(1 for line in source.splitlines() if "Rot(Z=" in line)
    assert rot_z_lines == 0, (
        f"expected no Rot(Z=) terms in polar-pattern emit; found {rot_z_lines}"
    )


def test_linear_pattern_uses_locations() -> None:
    """A uniform linear pattern should emit one ``Locations(...)`` (or
    ``GridLocations``) term, not a chain of ``Pos(i·dx, 0, 0)`` factors."""
    source = _translate("tests/fixtures/tier4_patterns/linear_pattern_holes.FCStd")
    assert "GridLocations(" in source or "Locations(" in source, (
        "expected a Locations context; emit still spells out positions"
    )
    # And the chained `Pos(i*dx, 0, 0) * extrude(...)` form should be gone.
    extrude_terms = source.count(" * extrude(")
    # The body chain itself uses one ``extrude(...)`` per Pad/Pocket; the
    # pattern should add exactly one more for the Locations multiplier.
    # If the spelled-out form is still emitted, ``* extrude(`` appears once
    # per extra copy (3 for a 4-occurrence linear pattern).
    assert extrude_terms <= 1, (
        f"emit still chains extrudes via Pos; found {extrude_terms} ` * extrude(` terms"
    )


# ---------------------------------------------------------------------------
# #76 — FreeCAD Labels should drive variable names + module docstring
# ---------------------------------------------------------------------------


def test_renamed_sketch_uses_label_as_variable_name() -> None:
    """The hex cap screw fixture renamed its hexagon sketch to ``Hexagon`` —
    the emit should reflect that, not call it ``sketch_001``."""
    source = _translate(
        "tests/fixtures/tier3_corpus/ANSI-ASME-B18_2_1_Hex_Head_Cap_Screw_1_4-20x1.FCStd"
    )
    # The default-named ``sketch_001`` should NOT appear; the Label-derived
    # name ``hexagon`` should.
    assert "sketch_001" not in source, (
        "emit still uses FreeCAD's autogenerated Name `sketch_001`; "
        "expected the user's Label `Hexagon`"
    )
    assert "hexagon" in source, (
        "emit doesn't carry the user-set Label `Hexagon` as a variable name"
    )


# ---------------------------------------------------------------------------
# #43 — solver-noise coordinates should be snapped
# ---------------------------------------------------------------------------


@pytest.mark.xfail(strict=True, reason="tracks #43 — coherent snap needs anchor-point refactor")
def test_partdesign_example_no_solver_noise_digits() -> None:
    """``partdesign_example`` contains user-typed `55` and `270` that the
    FreeCAD constraint solver settled at `54.9999786…` and `270.00003…`.
    The emit should snap these to the typed values (without breaking BRep
    validity — see the issue body for the failed naïve-snap experiment)."""
    source = _translate("tests/fixtures/tier2_partdesign/partdesign_example.FCStd")
    # No 10-significant-digit-near-round-integer literal should appear.
    bad_patterns = ["54.99997866", "270.0000349", "261.7867"]
    for pat in bad_patterns:
        assert pat not in source, (
            f"emit still contains solver-noise literal {pat!r}; expected snap to round value"
        )


# ---------------------------------------------------------------------------
# #77 — shared-helpers CLI flag should switch from inlining to importing
# ---------------------------------------------------------------------------


def test_shared_helpers_flag_emits_import_not_inline() -> None:
    """With ``--shared-helpers``, the emit should ``from fcstd2b123d.runtime
    import _edges_at, ...`` rather than inlining the helper definitions."""
    import os
    import subprocess

    env = {**os.environ, "PYTHONPATH":
           os.environ.get("FCSTD2B123D_FREECAD_PYTHONPATH", "") + ":"
           + str((__import__('pathlib').Path(__file__).parent.parent / "src"))}
    fc_py = os.environ.get("FCSTD2B123D_FREECAD_PYTHON")
    if not fc_py:
        pytest.skip("FCSTD2B123D_FREECAD_PYTHON not set")
    out = subprocess.run(
        [
            fc_py, "-m", "fcstd2b123d", "--shared-helpers",
            "tests/fixtures/tier3_corpus/ANSI-ASME-B18_2_1_Hex_Head_Cap_Screw_1_4-20x1.FCStd",
        ],
        capture_output=True, text=True, env=env, check=False,
    )
    assert out.returncode == 0, f"--shared-helpers translation failed:\n{out.stderr}"
    source = out.stdout
    assert "from fcstd2b123d.runtime import" in source, (
        "expected `from fcstd2b123d.runtime import ...` line"
    )
    # The inlined `def _edges_at` block should NOT appear when sharing.
    assert "def _edges_at(" not in source, (
        "emit still inlines _edges_at — flag had no effect"
    )


# ---------------------------------------------------------------------------
# #78 — builder-mode CLI flag should produce `with BuildSketch()` output
# ---------------------------------------------------------------------------
#
# Phase 1: sketches only — the ``--style=builder`` flag dispatches sketch
# translation through ``_translate_sketch_builder``, producing
# ``with BuildSketch(plane) as <var>: ...`` blocks followed by
# ``<var> = <var>.sketch`` so downstream Pad/Pocket/etc. still reference
# the variable name unchanged. Bodies remain algebra-style for now —
# phase 2 (BuildPart wrapping) is a separate piece of work.


def test_builder_mode_uses_with_buildsketch() -> None:
    """With ``--style=builder``, every sketch should emit a
    ``with BuildSketch(...) as <var>:`` block (phase 1)."""
    import os
    import subprocess

    fc_py = os.environ.get("FCSTD2B123D_FREECAD_PYTHON")
    if not fc_py:
        pytest.skip("FCSTD2B123D_FREECAD_PYTHON not set")
    env = {**os.environ, "PYTHONPATH":
           os.environ.get("FCSTD2B123D_FREECAD_PYTHONPATH", "") + ":"
           + str((__import__('pathlib').Path(__file__).parent.parent / "src"))}
    out = subprocess.run(
        [
            fc_py, "-m", "fcstd2b123d", "--style", "builder",
            "tests/fixtures/tier2_partdesign/simple_pad.FCStd",
        ],
        capture_output=True, text=True, env=env, check=False,
    )
    assert out.returncode == 0, f"--style=builder translation failed:\n{out.stderr}"
    source = out.stdout
    assert "with BuildSketch(" in source, (
        "expected `with BuildSketch(...)` block in builder-mode emit"
    )
    assert "BuildSketch" in source, "BuildSketch should be in the imports"
    # Rebinding pattern lets the rest of the body chain stay algebra-style
    # without renaming the variable.
    assert ".sketch" in source, (
        "expected `<var> = <var>.sketch` rebind so downstream extrude / "
        "revolve calls can use the sketch variable unchanged"
    )


def test_builder_and_algebra_emit_same_geometry() -> None:
    """Both ``--style=algebra`` (default) and ``--style=builder`` must
    produce shapes with the same volume on a representative slice of
    tier-2 fixtures (the corpus suite already gates the full set)."""
    import os
    import subprocess

    fc_py = os.environ.get("FCSTD2B123D_FREECAD_PYTHON")
    if not fc_py:
        pytest.skip("FCSTD2B123D_FREECAD_PYTHON not set")
    env = {**os.environ, "PYTHONPATH":
           os.environ.get("FCSTD2B123D_FREECAD_PYTHONPATH", "") + ":"
           + str((__import__('pathlib').Path(__file__).parent.parent / "src"))}

    fixtures = [
        "tests/fixtures/tier2_partdesign/simple_pad.FCStd",
        "tests/fixtures/tier2_partdesign/pad_with_hole.FCStd",
        "tests/fixtures/tier2_partdesign/pad_with_ellipse.FCStd",
    ]
    for fx in fixtures:
        vols: dict[str, float] = {}
        for style in ("algebra", "builder"):
            translate = subprocess.run(
                [fc_py, "-m", "fcstd2b123d", "--style", style, fx],
                capture_output=True, text=True, env=env, check=False,
            )
            assert translate.returncode == 0, (
                f"{style} translate failed on {fx}:\n{translate.stderr}"
            )
            exec_out = subprocess.run(
                [".venv/bin/python", "-c",
                 translate.stdout + "\nprint('VOL:', result.volume)"],
                capture_output=True, text=True, check=False,
            )
            assert exec_out.returncode == 0, (
                f"{style} exec failed on {fx}:\n{exec_out.stderr}"
            )
            for line in exec_out.stdout.splitlines():
                if line.startswith("VOL:"):
                    vols[style] = float(line.split()[1])
                    break
        rel_err = abs(vols["algebra"] - vols["builder"]) / max(
            abs(vols["algebra"]), 1e-9
        )
        assert rel_err < 1e-6, (
            f"{fx}: algebra={vols['algebra']} builder={vols['builder']} "
            f"(rel.err={rel_err})"
        )
