"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Angle_Bar_60x40x5_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (60, 0), (60, 2))
    + CenterArc(center=(57, 2), radius=3, start_angle=0, arc_size=90)
    + Line((57, 5), (11, 5))
    + CenterArc(center=(11, 11), radius=6, start_angle=270, arc_size=-90)
    + Line((5, 11), (5, 37))
    + CenterArc(center=(2, 37), radius=3, start_angle=0, arc_size=90)
    + Polyline((2, 40), (0, 40), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar 60x40x5 EN10056 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
