"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Angle_Bar_L200x200x24_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (200, 0), (200, 15))
    + CenterArc(center=(191, 15), radius=9, start_angle=0, arc_size=90)
    + Line((191, 24), (42, 24))
    + CenterArc(center=(42, 42), radius=18, start_angle=270, arc_size=-90)
    + Line((24, 42), (24, 191))
    + CenterArc(center=(15, 191), radius=9, start_angle=0, arc_size=90)
    + Polyline((15, 200), (0, 200), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar L200x200x24 EN10056 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
