"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Angle_Bar_L90x90x7_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (90, 0), (90, 2))
    + CenterArc(center=(85, 2), radius=5, start_angle=0, arc_size=90)
    + Line((85, 7), (17, 7))
    + CenterArc(center=(17, 17), radius=10, start_angle=270, arc_size=-90)
    + Line((7, 17), (7, 85))
    + CenterArc(center=(2, 85), radius=5, start_angle=0, arc_size=90)
    + Polyline((2, 90), (0, 90), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar L90x90x7 EN10056 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
