"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Angle_Bar_160x100x12_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (160, 0), (160, 5.5))
    + CenterArc(center=(153.5, 5.5), radius=6.5, start_angle=0, arc_size=90)
    + Line((153.5, 12), (25, 12))
    + CenterArc(center=(25, 25), radius=13, start_angle=270, arc_size=-90)
    + Line((12, 25), (12, 93.5))
    + CenterArc(center=(5.5, 93.5), radius=6.5, start_angle=0, arc_size=90)
    + Polyline((5.5, 100), (0, 100), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar 160x100x12 EN10056 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
