"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/ANSI-ASME-B18_2_2_Hex_Nut_1_4-20.FCStd."""

from build123d import (
    Axis,
    Circle,
    Edge,
    Plane,
    Polyline,
    Sketch,
    chamfer,
    extrude,
    make_face,
    revolve,
)
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated Fillet / chamfer_0 features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 6 lines (1 loops)
sketch_profile = Polyline(
    (0, 5.2),
    (5.55625, 5.2),
    (6.4158, 4.703738715947),
    (6.4158, 0.4962612840520002),
    (5.55625, 0),
    (0, 0),
    (0, 5.2),
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_profile)
)

# PartDesign::Revolution 'Revolution': angle=360.0
revolution = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Hexagon': 7 lines, 1 circle (2 loops)
sketch_001_profile = Polyline(
    (-5.55625, 3.207902433185),
    (0, 6.41580486637),
    (5.55625, 3.207902433185),
    (5.55625, -3.207902433185),
    (0, -6.41580486637),
    (-5.55625, -3.207902433185),
    (-5.55625, 3.207902433185),
)
sketch_001 = Sketch() + Plane(
    origin=(0, 0, 5.200000000000002), x_dir=(-1, 0, 0), z_dir=(0, 0, 1)
) * (Circle(7.41580486637) - make_face(sketch_001_profile))

# Sketcher::SketchObject 'Sketch002': 1 circle (1 loops)
sketch_002 = Sketch() + Plane(origin=(0, 0, 5.2), x_dir=(-1, 0, 0), z_dir=(0, 0, 1)) * (
    Circle(3.175)
)

# PartDesign::Pocket 'Pocket' (body-less, ThroughAll)
pocket = revolution - extrude(sketch_001, amount=-1000000.0)

# PartDesign::Pocket 'Pocket001' (body-less, ThroughAll)
pocket_001 = pocket - extrude(sketch_002, amount=-1000000.0)

# PartDesign::Chamfer 'Chamfer': size=0.5 on 2 edges of Pocket001
chamfer_0 = chamfer(
    _edges_at(
        pocket_001, [(3.175, 0, 5.2), (2.2450640302672884, 2.245064030267288, 0)]
    ),
    length=0.5,
)

result = chamfer_0
