"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/arduinounomissmetal.FCStd."""

from build123d import import_step
from pathlib import Path

try:
    _HERE = Path(__file__).resolve().parent
except NameError:
    # When the module is exec'd from a string (e.g. by a test harness)
    # ``__file__`` isn't bound; fall back to the current working directory
    # so the STEP-sidecar paths still resolve when callers set up cwd.
    _HERE = Path.cwd()

# Part::Feature 'arduino_uno': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno = import_step(str(_HERE / "arduinounomissmetal.arduino_uno.step"))

# Part::Feature 'arduino_uno001': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_001 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_001.step"))

# Part::Feature 'arduino_uno002': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_002 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_002.step"))

# Part::Feature 'arduino_uno003': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_003 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_003.step"))

# Part::Feature 'arduino_uno004': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_004 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_004.step"))

# Part::Feature 'arduino_uno005': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_005 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_005.step"))

# Part::Feature 'arduino_uno006': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_006 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_006.step"))

# Part::Feature 'arduino_uno007': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_007 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_007.step"))

# Part::Feature 'arduino_uno008': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_008 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_008.step"))

# Part::Feature 'arduino_uno009': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_009 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_009.step"))

# Part::Feature 'arduino_uno010': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_010 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_010.step"))

# Part::Feature 'arduino_uno011': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_011 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_011.step"))

# Part::Feature 'arduino_uno012': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_012 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_012.step"))

# Part::Feature 'arduino_uno013': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_013 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_013.step"))

# Part::Feature 'arduino_uno014': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_014 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_014.step"))

# Part::Feature 'arduino_uno015': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_015 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_015.step"))

# Part::Feature 'arduino_uno016': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_016 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_016.step"))

# Part::Feature 'arduino_uno017': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_017 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_017.step"))

# Part::Feature 'arduino_uno018': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_018 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_018.step"))

# Part::Feature 'arduino_uno019': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_019 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_019.step"))

# Part::Feature 'arduino_uno020': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_020 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_020.step"))

# Part::Feature 'arduino_uno021': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_021 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_021.step"))

# Part::Feature 'arduino_uno022': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_022 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_022.step"))

# Part::Feature 'arduino_uno023': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_023 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_023.step"))

# Part::Feature 'arduino_uno024': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_024 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_024.step"))

# Part::Feature 'arduino_uno025': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_025 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_025.step"))

# Part::Feature 'arduino_uno026': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_026 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_026.step"))

# Part::Feature 'arduino_uno027': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_027 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_027.step"))

# Part::Feature 'arduino_uno028': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_028 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_028.step"))

# Part::Feature 'arduino_uno029': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_029 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_029.step"))

# Part::Feature 'arduino_uno030': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_030 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_030.step"))

# Part::Feature 'arduino_uno031': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_031 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_031.step"))

# Part::Feature 'arduino_uno032': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_032 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_032.step"))

# Part::Feature 'arduino_uno033': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_033 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_033.step"))

# Part::Feature 'arduino_uno034': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_034 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_034.step"))

# Part::Feature 'arduino_uno035': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_035 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_035.step"))

# Part::Feature 'arduino_uno036': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_036 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_036.step"))

# Part::Feature 'arduino_uno037': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_037 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_037.step"))

# Part::Feature 'arduino_uno038': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_038 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_038.step"))

# Part::Feature 'arduino_uno039': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_039 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_039.step"))

# Part::Feature 'arduino_uno040': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_040 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_040.step"))

# Part::Feature 'arduino_uno041': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_041 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_041.step"))

# Part::Feature 'arduino_uno042': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_042 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_042.step"))

# Part::Feature 'arduino_uno043': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_043 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_043.step"))

# Part::Feature 'arduino_uno044': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_044 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_044.step"))

# Part::Feature 'arduino_uno045': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_045 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_045.step"))

# Part::Feature 'arduino_uno046': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_046 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_046.step"))

# Part::Feature 'arduino_uno047': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_047 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_047.step"))

# Part::Feature 'arduino_uno048': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_048 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_048.step"))

# Part::Feature 'arduino_uno049': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_049 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_049.step"))

# Part::Feature 'arduino_uno050': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_050 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_050.step"))

# Part::Feature 'arduino_uno051': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_051 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_051.step"))

# Part::Feature 'arduino_uno052': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_052 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_052.step"))

# Part::Feature 'arduino_uno053': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_053 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_053.step"))

# Part::Feature 'arduino_uno054': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_054 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_054.step"))

# Part::Feature 'arduino_uno055': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_055 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_055.step"))

# Part::Feature 'arduino_uno056': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_056 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_056.step"))

# Part::Feature 'arduino_uno057': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_057 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_057.step"))

# Part::Feature 'arduino_uno058': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_058 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_058.step"))

# Part::Feature 'arduino_uno059': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_059 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_059.step"))

# Part::Feature 'arduino_uno060': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_060 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_060.step"))

# Part::Feature 'arduino_uno061': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_061 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_061.step"))

# Part::Feature 'arduino_uno062': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_062 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_062.step"))

# Part::Feature 'arduino_uno063': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_063 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_063.step"))

# Part::Feature 'arduino_uno064': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_064 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_064.step"))

# Part::Feature 'arduino_uno065': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_065 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_065.step"))

# Part::Feature 'arduino_uno066': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_066 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_066.step"))

# Part::Feature 'arduino_uno067': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_067 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_067.step"))

# Part::Feature 'arduino_uno068': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_068 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_068.step"))

# Part::Feature 'arduino_uno069': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_069 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_069.step"))

# Part::Feature 'arduino_uno070': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_070 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_070.step"))

# Part::Feature 'arduino_uno071': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_071 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_071.step"))

# Part::Feature 'arduino_uno072': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_072 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_072.step"))

# Part::Feature 'arduino_uno073': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_073 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_073.step"))

# Part::Feature 'arduino_uno074': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_074 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_074.step"))

# Part::Feature 'arduino_uno075': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_075 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_075.step"))

# Part::Feature 'arduino_uno076': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_076 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_076.step"))

# Part::Feature 'arduino_uno077': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_077 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_077.step"))

# Part::Feature 'arduino_uno078': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_078 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_078.step"))

# Part::Feature 'arduino_uno079': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_079 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_079.step"))

# Part::Feature 'arduino_uno080': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_080 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_080.step"))

# Part::Feature 'arduino_uno081': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_081 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_081.step"))

# Part::Feature 'arduino_uno082': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_082 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_082.step"))

# Part::Feature 'arduino_uno083': shape-import fallback (parametric history not preserved; geometry from STEP sidecar)
arduino_uno_083 = import_step(str(_HERE / "arduinounomissmetal.arduino_uno_083.step"))

result = arduino_uno_083
