"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/cabin_door.FCStd."""

from build123d import (
    CenterArc,
    Circle,
    Plane,
    Polyline,
    Pos,
    Sketch,
    extrude,
    make_face,
)

# Sketcher::SketchObject 'Sketch': 13 lines, 1 arc (2 loops)
sketch_loop_0 = (
    Polyline(
        (0, 0),
        (0, 70),
        (45, 70),
        (50.35898384862243, 45),
        (85, 40),
        (85, 0),
        (70, 0),
        (70, 7),
    )
    + CenterArc(
        center=(52.50000000000001, 6.999999686767261),
        radius=17.5,
        start_angle=1.025537936727262e-06,
        arc_size=179.99999794892415,
    )
    + Polyline((35, 7), (35, 0), (0, 0))
)
sketch_loop_1 = Polyline(
    (15, 60), (15, 45), (35, 45), (31.784609690826542, 60), (15, 60)
)
sketch = make_face(sketch_loop_0) - make_face(sketch_loop_1)

# PartDesign::Pad 'Pad': length=10.0
pad = extrude(sketch, amount=10)

# Sketcher::SketchObject 'Sketch001': 1 line, 8 circles (8 loops)
sketch_001 = Sketch() + Plane(origin=(0, 0, 10), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    (
        (Pos(5, 5) * Circle(1.25))
        + (Pos(5, 35) * Circle(1.25))
        + (Pos(5, 65) * Circle(1.25))
        + (Pos(40, 65) * Circle(1.25))
        + (Pos(57.06777302391767, 38.979854835517486) * Circle(1.25))
        + (Pos(76.86263939613342, 36.12271197837463) * Circle(1.25))
        + (Pos(77.50000000000001, 15) * Circle(1.25))
        + (Pos(31.500000000000004, 15) * Circle(1.25))
    )
)

# PartDesign::Pocket 'Pocket': length=10.0
pocket = pad - extrude(sketch_001, amount=-10)

# Sketcher::SketchObject 'Sketch002': 1 circle (1 loops)
sketch_002 = Sketch() + Plane(origin=(85, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    (Pos(35, 5) * Circle(1.25))
)

# PartDesign::Pocket 'Pocket001': length=5.0
pocket_001 = pocket - extrude(sketch_002, amount=-5)

result = pocket_001
