"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/DIN463_M33TabWasher.FCStd."""

from build123d import CenterArc, Circle, Edge, Polyline, extrude, fillet, make_face
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 6 lines, 2 arcs, 1 circle (2 loops)
sketch_profile = (
    Polyline((-26.532998322843, -14), (-56, -14), (-56, 14), (-26.532998322843, 14))
    + CenterArc(
        center=(0, 0),
        radius=30,
        start_angle=512.1818607153582,
        arc_size=-214.36372143072032,
    )
    + Polyline((14, -26.532998322845), (14, -34), (-14, -34), (-14, -26.532998322845))
    + CenterArc(
        center=(0, 0),
        radius=30,
        start_angle=242.1818607153404,
        arc_size=-34.363721430708495,
    )
)
sketch = make_face(sketch_profile) - Circle(17)

# PartDesign::Pad 'Pad': length=1.6
pad = extrude(sketch, amount=1.6)

# PartDesign::Fillet 'Fillet': radius=10.0 on 1 edges of Pad
fillet_0 = fillet(_edges_at(pad, [(-26.53299832284319, 14, 0.8)]), radius=10)

# PartDesign::Fillet 'Fillet001': radius=1.0 on 1 edges of Fillet
fillet_001 = fillet(_edges_at(fillet_0, [(14, -26.532998322844385, 0.8)]), radius=1)

result = fillet_001
