"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/DIN440_CLASS_V_M5.FCStd."""

from build123d import Circle, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines, 1 circle (2 loops)
sketch_profile = Polyline(
    (-2.75, 2.75), (2.75, 2.75), (2.75, -2.75), (-2.75, -2.75), (-2.75, 2.75)
)
sketch = Circle(9) - make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=2.0
pad = extrude(sketch, amount=2)

result = pad
