"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Flat_Bar_60x25_EN10058_S235JR.FCStd."""

from build123d import Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline(
    (-30, -12.5), (30, -12.5), (30, 12.5), (-30, 12.5), (-30, -12.5)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Flat Bar 60x25 EN10058 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
