"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Flat_Bar_120x20_EN10058_S235JR.FCStd."""

from build123d import Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline((-60, -10), (60, -10), (60, 10), (-60, 10), (-60, -10))
sketch = make_face(sketch_profile)

# Part::Extrusion 'Flat Bar 120x20 EN10058 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
