"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/FootPAD.FCStd."""

from build123d import Axis, Edge, Plane, Polyline, Sketch, fillet, make_face, revolve
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 6 lines (1 loops)
sketch_profile = Polyline(
    (-17.5, 0), (-13, -24), (-6, -24), (-6, -15), (-2.5, -15), (-2.5, 0), (-17.5, 0)
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_profile)
)

# PartDesign::Revolution 'Revolution': angle=360.0
revolution = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# PartDesign::Fillet 'Fillet': radius=5.0 on 1 edges of Revolution
fillet_0 = fillet(_edges_at(revolution, [(13, 0, -24)]), radius=5)

result = fillet_0
