"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/GenericTable_1x2m.FCStd."""

from build123d import Edge, Plane, Polyline, Sketch, extrude, fillet, make_face
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline((0, 0), (2000, 0), (2000, 1000), (0, 1000), (0, 0))
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=50.0
pad = extrude(sketch, amount=50)

# Sketcher::SketchObject 'Sketch001': 4 lines (1 loops)
sketch_001_profile = Polyline(
    (150, -150), (250, -150), (250, -250), (150, -250), (150, -150)
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, -1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pad 'Pad001': length=900.0
pad_001 = pad + extrude(sketch_001, amount=900)

# Sketcher::SketchObject 'Sketch002': 4 lines (1 loops)
sketch_002_profile = Polyline(
    (1750, -150), (1850, -150), (1850, -250), (1750, -250), (1750, -150)
)
sketch_002 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, -1)) * (
    make_face(sketch_002_profile)
)

# PartDesign::Pad 'Pad002': length=900.0
pad_002 = pad_001 + extrude(sketch_002, amount=900)

# Sketcher::SketchObject 'Sketch003': 4 lines (1 loops)
sketch_003_profile = Polyline(
    (150, -750), (250, -750), (250, -850), (150, -850), (150, -750)
)
sketch_003 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, -1)) * (
    make_face(sketch_003_profile)
)

# PartDesign::Pad 'Pad003': length=900.0
pad_003 = pad_002 + extrude(sketch_003, amount=900)

# Sketcher::SketchObject 'Sketch004': 4 lines (1 loops)
sketch_004_profile = Polyline(
    (1750, -750), (1850, -750), (1850, -850), (1750, -850), (1750, -750)
)
sketch_004 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, -1)) * (
    make_face(sketch_004_profile)
)

# PartDesign::Pad 'Pad004': length=900.0
pad_004 = pad_003 + extrude(sketch_004, amount=900)

# PartDesign::Fillet 'Fillet': radius=45.0 on 1 edges of Pad004
fillet_0 = fillet(
    _edges_at(
        pad_004, [(1000, 0, 50), (2000, 500, 50), (1000, 1000, 50), (0, 500, 50)]
    ),
    radius=45,
)

result = fillet_0
