"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/HE-B-Profile_280_DIN1025-2_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 12 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((5.25, -98), (5.25, 98))
    + CenterArc(center=(29.25, 98), radius=24, start_angle=180, arc_size=-90)
    + Polyline(
        (29.25, 122), (140, 122), (140, 140), (-140, 140), (-140, 122), (-29.25, 122)
    )
    + CenterArc(center=(-29.25, 98), radius=24, start_angle=90, arc_size=-90)
    + Line((-5.25, 98), (-5.25, -98))
    + CenterArc(center=(-29.25, -98), radius=24, start_angle=360, arc_size=-90)
    + Polyline(
        (-29.25, -122),
        (-140, -122),
        (-140, -140),
        (140, -140),
        (140, -122),
        (29.25, -122),
    )
    + CenterArc(center=(29.25, -98), radius=24, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'HE-B-Profile 280 DIN1025-2 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
