"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/HE-M-Profile_220_DIN1025-4_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 12 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((7.750000000025, -76), (7.750000000025, 76))
    + CenterArc(center=(25.750000000025, 76), radius=18, start_angle=180, arc_size=-90)
    + Polyline(
        (25.750000000015, 94),
        (113, 94),
        (113, 120),
        (-113, 120),
        (-113, 94),
        (-25.750000000027, 94),
    )
    + CenterArc(center=(-25.750000000027, 76), radius=18, start_angle=90, arc_size=-90)
    + Line((-7.750000000027, 76), (-7.750000000027, -76))
    + CenterArc(
        center=(-25.750000000027, -76), radius=18, start_angle=360, arc_size=-90
    )
    + Polyline(
        (-25.750000000035, -94),
        (-113, -94),
        (-113, -120),
        (113, -120),
        (113, -94),
        (25.750000000026006, -94),
    )
    + CenterArc(center=(25.750000000026, -76), radius=18, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'HE-M-Profile 220 DIN1025-4 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
