"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/IPE-Profile_140_DIN1025-5_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 12 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((2.35, -56.1), (2.35, 56.1))
    + CenterArc(center=(9.35, 56.1), radius=7, start_angle=180, arc_size=-90)
    + Polyline(
        (9.35, 63.1),
        (36.5, 63.1),
        (36.5, 70),
        (-36.5, 70),
        (-36.5, 63.1),
        (-9.350000000000001, 63.1),
    )
    + CenterArc(center=(-9.35, 56.1), radius=7, start_angle=90, arc_size=-90)
    + Line((-2.35, 56.1), (-2.35, -56.1))
    + CenterArc(center=(-9.35, -56.1), radius=7, start_angle=360, arc_size=-90)
    + Polyline(
        (-9.35, -63.1),
        (-36.5, -63.1),
        (-36.5, -70),
        (36.5, -70),
        (36.5, -63.1),
        (9.350000000000001, -63.1),
    )
    + CenterArc(center=(9.35, -56.1), radius=7, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'IPE-Profile 140 DIN1025-5 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
