"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/ISO7093DIN9021_M24FlatWasher.FCStd."""

from build123d import Circle, extrude

# Sketcher::SketchObject 'Sketch': 2 circles (2 loops)
sketch = Circle(36) - Circle(14)

# PartDesign::Pad 'Pad': length=5.0
pad = extrude(sketch, amount=5)

result = pad
