"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/M20CloseMax.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=10.605, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(10.605, 15)

result = cylinder
