"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/M30NormalMax.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=16.695, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(16.695, 15)

result = cylinder
