"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/M56NormalMin.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=31.0, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(31, 15)

result = cylinder
