"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/M6LooseMin.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=3.5, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(3.5, 15)

result = cylinder
