"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/M6LooseMean.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=3.59, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(3.59, 15)

result = cylinder
