"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/M80NormalMean.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=43.135000000000005, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(43.135000000000005, 15)

result = cylinder
