"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/makerbeam_bracket_corner.FCStd."""

from build123d import (
    CenterArc,
    Circle,
    Plane,
    Polyline,
    Pos,
    Sketch,
    extrude,
    make_face,
)

# Sketcher::SketchObject 'Sketch': 6 lines, 2 arcs (1 loops)
sketch_profile = (
    Polyline(
        (-2.4999991830127613, 0), (-32.6, 0), (-32.6, -1.5), (-2.49999967320511, -1.5)
    )
    + CenterArc(
        center=(-2.500000000000017, -2.4999999999999636),
        radius=1,
        start_angle=89.99998127603115,
        arc_size=-89.99998127603222,
    )
    + Polyline(
        (-1.5, -2.499999999999963),
        (-1.5, -32.60000000000008),
        (0, -32.60000000000008),
        (0, -2.499999999999993),
    )
    + CenterArc(
        center=(-2.500000000000017, -2.4999999999999636),
        radius=2.500000000000017,
        start_angle=0,
        arc_size=89.99998127603205,
    )
)
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=10.0
pad = extrude(sketch, amount=5, both=True)

# Sketcher::SketchObject 'Sketch001': 2 circles (2 loops)
sketch_001 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    ((Pos(-27.6, 0) * Circle(1.5)) + (Pos(-17.6, 0) * Circle(1.5)))
)

# PartDesign::Pocket 'Pocket': length=5.0
pocket = pad - extrude(sketch_001, amount=-5)

# Sketcher::SketchObject 'Sketch002': 2 circles (2 loops)
sketch_002 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    ((Pos(-27.6, 0) * Circle(1.5)) + (Pos(-17.6, 0) * Circle(1.5)))
)

# PartDesign::Pocket 'Pocket001': length=5.0 (reversed)
pocket_001 = pocket - extrude(sketch_002, amount=5)

result = pocket_001
