"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Profile-40x40L-I-Type_Slot8.FCStd."""

from build123d import CenterArc, Circle, Line, Plane, Rot, Sketch, extrude, make_face


def _pattern_difference(base, *removals):
    """Boolean-subtract each removal from ``base`` via BuildPart.

    Mirror of ``_pattern_union`` for subtractive (pocket Original) patterns.
    Chained ``-`` does *not* exhibit the same Compound-collapsing bug as
    ``+`` in current build123d, but using BuildPart for both keeps the emit
    symmetric and future-proofs against the inverse issue.
    """
    from build123d import BuildPart, Mode, add

    with BuildPart() as _bp:
        add(base)
        for s in removals:
            add(s, mode=Mode.SUBTRACT)
    return _bp.part


# Sketcher::SketchObject 'Sketch': 4 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((-16, 20), (16, 20))
    + CenterArc(center=(16, 16), radius=4, start_angle=90, arc_size=-90)
    + Line((20, 16), (20, -16))
    + CenterArc(center=(16, -16), radius=4, start_angle=360, arc_size=-90)
    + Line((16, -20), (-16, -20))
    + CenterArc(center=(-16, -16), radius=4, start_angle=270, arc_size=-90)
    + Line((-20, -16), (-20, 16))
    + CenterArc(center=(-16, 16), radius=4, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Solid_Material': length=100.0
pad = extrude(sketch, amount=100)

# Sketcher::SketchObject 'Sketch001': 16 lines, 18 arcs (2 loops)
sketch_001_loop_0 = (
    Line((-16, 18.2), (-12.299999999999999, 18.2))
    + CenterArc(
        center=(-12.299999999999999, 17.7), radius=0.5, start_angle=90, arc_size=-90
    )
    + Line((-11.799999999999999, 17.7), (-11.799999999999999, 12.299999999999999))
    + CenterArc(
        center=(-12.299999999999999, 12.299999999999999),
        radius=0.5,
        start_angle=360,
        arc_size=-90,
    )
    + Line((-12.299999999999999, 11.799999999999999), (-17.7, 11.799999999999999))
    + CenterArc(
        center=(-17.7, 12.299999999999999), radius=0.5, start_angle=270, arc_size=-90
    )
    + Line((-18.2, 12.299999999999999), (-18.2, 16))
    + CenterArc(center=(-16, 16), radius=2.2, start_angle=180, arc_size=-90)
)
sketch_001_loop_1 = (
    CenterArc(
        center=(-5.500000000864618, 18.5),
        radius=1.5,
        start_angle=0,
        arc_size=90.00000241803154,
    )
    + Line((-5.500000064168536, 20), (5.500000064168536, 20))
    + CenterArc(
        center=(5.499999999135383, 18.5),
        radius=1.5,
        start_angle=89.99999751591655,
        arc_size=90.0000024840834,
    )
    + Line((4, 18.5), (4, 16.5))
    + CenterArc(center=(5, 16.5), radius=1, start_angle=180, arc_size=90)
    + Line((5, 15.5), (6.499999999135383, 15.5))
    + CenterArc(
        center=(6.499999999135383, 16), radius=0.5, start_angle=270, arc_size=90
    )
    + Line((7, 16), (7, 17.5))
    + CenterArc(
        center=(7.499999999135383, 17.5),
        radius=0.5,
        start_angle=180,
        arc_size=-89.99999997523057,
    )
    + CenterArc(
        center=(7.499999999999999, 15.499999999999996),
        radius=2.5,
        start_angle=90.00000002476945,
        arc_size=-90.00000002476939,
    )
    + Line((10, 15.499999999999998), (10, 14.189999999999998))
    + CenterArc(center=(5, 14.189999999999994), radius=5, start_angle=360, arc_size=-45)
    + Line(
        (8.535533905932734, 10.654466094067251), (7.095533905932731, 9.214466094067255)
    )
    + CenterArc(center=(3.56, 12.75), radius=5, start_angle=315, arc_size=-45)
    + Line((3.559999999999999, 7.75), (-3.560000000000001, 7.749999999999999))
    + CenterArc(
        center=(-3.56, 12.749999999999998), radius=5, start_angle=270, arc_size=-45
    )
    + Line(
        (-7.095533905932737, 9.21446609406726), (-8.535533905932738, 10.65446609406726)
    )
    + CenterArc(
        center=(-5, 14.189999999999998), radius=5, start_angle=225, arc_size=-45
    )
    + Line((-10, 14.189999999999998), (-10, 15.499999999999998))
    + CenterArc(
        center=(-7.499999999999999, 15.499999999999998),
        radius=2.5,
        start_angle=180,
        arc_size=-89.99999997523051,
    )
    + CenterArc(
        center=(-7.500000000864618, 17.5),
        radius=0.5,
        start_angle=90.00000002476946,
        arc_size=-90.00000002476952,
    )
    + Line((-7, 17.5), (-7, 16))
    + CenterArc(
        center=(-6.500000000864618, 16), radius=0.5, start_angle=180, arc_size=90
    )
    + Line((-6.500000000864618, 15.499999999999998), (-5, 15.499999999999998))
    + CenterArc(center=(-5, 16.5), radius=1, start_angle=270, arc_size=90)
    + Line((-4, 16.5), (-4, 18.5))
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 100), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    (make_face(sketch_001_loop_0) + make_face(sketch_001_loop_1))
)

# PartDesign::Pocket 'Pocket': ThroughAll
pocket = pad - extrude(sketch_001, amount=-1000000)

# PartDesign::PolarPattern 'PolarPattern': PolarPattern around (0, 0, 1), step=90.0deg, occurrences=4
polar_pattern = _pattern_difference(
    pocket,
    Rot(Z=90) * extrude(sketch_001, amount=-1000000),
    Rot(Z=180) * extrude(sketch_001, amount=-1000000),
    Rot(Z=270) * extrude(sketch_001, amount=-1000000),
)

# Sketcher::SketchObject 'Sketch002': 1 circle (1 loops)
sketch_002 = Sketch() + Plane(origin=(0, 0, 100), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    Circle(3.4)
)

# PartDesign::Pocket 'Pocket001': ThroughAll
pocket_001 = polar_pattern - extrude(sketch_002, amount=-1000000)

result = pocket_001
