"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Rectangular_hollow_section_250x150x10_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-55, 115), (55, 115))
    + CenterArc(center=(55, 105), radius=10, start_angle=90, arc_size=-90)
    + Line((65, 105), (65, -105))
    + CenterArc(center=(55, -105), radius=10, start_angle=360, arc_size=-90)
    + Line((55, -115), (-55, -115))
    + CenterArc(center=(-55, -105), radius=10, start_angle=270, arc_size=-90)
    + Line((-65, -105), (-65, 105))
    + CenterArc(center=(-55, 105), radius=10, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-60, 125), (60, 125))
    + CenterArc(center=(60, 110), radius=15, start_angle=90, arc_size=-90)
    + Line((75, 110), (75, -110))
    + CenterArc(center=(60, -110), radius=15, start_angle=360, arc_size=-90)
    + Line((60, -125), (-60, -125))
    + CenterArc(center=(-60, -110), radius=15, start_angle=270, arc_size=-90)
    + Line((-75, -110), (-75, 110))
    + CenterArc(center=(-60, 110), radius=15, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 250x150x10 EN10219 S235JRH': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
