"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Rectangular_hollow_section_500x300x20_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-110, 230), (110, 230))
    + CenterArc(center=(110, 210), radius=20, start_angle=90, arc_size=-90)
    + Line((130, 210), (130, -210))
    + CenterArc(center=(110, -210), radius=20, start_angle=360, arc_size=-90)
    + Line((110, -230), (-110, -230))
    + CenterArc(center=(-110, -210), radius=20, start_angle=270, arc_size=-90)
    + Line((-130, -210), (-130, 210))
    + CenterArc(center=(-110, 210), radius=20, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-120, 250), (120, 250))
    + CenterArc(center=(120, 220), radius=30, start_angle=90, arc_size=-90)
    + Line((150, 220), (150, -220))
    + CenterArc(center=(120, -220), radius=30, start_angle=360, arc_size=-90)
    + Line((120, -250), (-120, -250))
    + CenterArc(center=(-120, -220), radius=30, start_angle=270, arc_size=-90)
    + Line((-150, -220), (-150, 220))
    + CenterArc(center=(-120, 220), radius=30, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 500x300x20 EN10219 S235JRH': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
