"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/rotary-resistor-M64W103KB40.FCStd."""

from build123d import Circle, Plane, Polyline, Pos, Sketch, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline(
    (-7.9, 0),
    (1.8000000000000007, 0),
    (1.8, -9.7),
    (-7.900000000000001, -9.7),
    (-7.9, 0),
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_profile)
)

# PartDesign::Pad 'Pad': length=4.7
pad = extrude(sketch, amount=2.35, both=True)

# Sketcher::SketchObject 'Sketch001': 1 circle (1 loops)
sketch_001 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(-1, 0, 0), z_dir=(0, 0, 1)) * (
    (Pos(0, 1.2) * Circle(1.1))
)

# PartDesign::Pad 'Pad001': length=1.3
pad_001 = pad + extrude(sketch_001, amount=1.3)

# Sketcher::SketchObject 'Sketch002': 4 lines (1 loops)
sketch_002_profile = Polyline(
    (-1.5, 1.45), (1.5, 1.45), (1.5, 0.95), (-1.5, 0.95), (-1.5, 1.45)
)
sketch_002 = Sketch() + Plane(origin=(0, 0, 1.3), x_dir=(-1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_002_profile)
)

# PartDesign::Pocket 'Pocket' (body-less, chained from PartDesign::Pad): length=0.5
pocket = pad_001 - extrude(sketch_002, amount=-0.5)

# Sketcher::SketchObject 'Sketch003': 3 circles (3 loops)
sketch_003 = Sketch() + Plane(
    origin=(0, 0, -9.699999999999996), x_dir=(1, 0, 0), z_dir=(0, 0, -1)
) * (
    (
        (Pos(-5.32, 0) * Circle(0.25))
        + (Pos(-3.05, 0) * Circle(0.25))
        + (Pos(-0.78, 0) * Circle(0.25))
    )
)

# PartDesign::Pad 'Pad002': length=5.0
pad_002 = pocket + extrude(sketch_003, amount=5)

result = pad_002
