"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Round_Bar_8_EN10060_S235JR.FCStd."""

from build123d import Circle, extrude

# Sketcher::SketchObject 'Sketch': 1 circle (1 loops)
sketch = Circle(4)

# Part::Extrusion 'Round Bar 8 EN10060 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
