"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Screw_M6x30_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((2.999, 0), (5, 0), (5, 5.97229))
    + CenterArc(center=(4.97229, 5.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline((4.97229, 6), (0, 6), (0, -30), (2, -30), (3, -29), (3, -6), (2.999, 0))
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (2.9213923621, 0),
    (1.46069618105, 2.53),
    (-1.46069618105, 2.53),
    (-2.9213923621, 0),
    (-1.46069618105, -2.53),
    (1.46069618105, -2.53),
    (2.9213923621, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 6), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M6x30 ISO4762 8,8 A2K' (body-less, standalone): length=5.06
pocket = extrude(sketch_001, amount=-5.06)

result = pocket
