"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Screw_M16x200_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((7.999, 0), (12, 0), (12, 15.97229))
    + CenterArc(center=(11.97229, 15.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (11.97229, 16), (0, 16), (0, -200), (6, -200), (8, -198), (8, -156), (7.999, 0)
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (8.12909179019, 0),
    (4.064545895095, 7.04),
    (-4.064545895095, 7.04),
    (-8.12909179019, 0),
    (-4.064545895095, -7.04),
    (4.064545895095, -7.04),
    (8.12909179019, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 16), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M16x200 ISO4762 8,8 A2K' (body-less, standalone): length=14.08
pocket = extrude(sketch_001, amount=-14.08)

result = pocket
