"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Screw_M12x90_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((5.999, 0), (9, 0), (9, 11.97229))
    + CenterArc(center=(8.97229, 11.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (8.97229, 12), (0, 12), (0, -90), (4.25, -90), (6, -88.25), (6, -54), (5.999, 0)
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (5.81391721074, 0),
    (2.90695860537, 5.035),
    (-2.90695860537, 5.035),
    (-5.81391721074, 0),
    (-2.90695860537, -5.035),
    (2.9069586053689997, -5.035),
    (5.81391721074, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 12), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M12x90 ISO4762 8,8 A2K' (body-less, standalone): length=10.07
pocket = extrude(sketch_001, amount=-10.07)

result = pocket
