"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Screw_M1_6x8_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((0.799, 0), (1.5, 0), (1.5, 1.57229))
    + CenterArc(center=(1.47229, 1.57229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (1.47229, 1.6),
        (0, 1.6),
        (0, -8),
        (0.45, -8),
        (0.8, -7.65),
        (0.8, -0.2),
        (0.799, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (0.900666419936, 0),
    (0.4503332099680001, 0.78),
    (-0.450333209968, 0.78),
    (-0.9006664199359999, 0),
    (-0.4503332099680001, -0.78),
    (0.450333209968, -0.78),
    (0.9006664199359999, 0),
)
sketch_001 = Sketch() + Plane(
    origin=(0, 0, 1.5999999999999999), x_dir=(1, 0, 0), z_dir=(0, 0, 1)
) * (make_face(sketch_001_profile))

# PartDesign::Pocket 'Screw M1,6x8 ISO4762 8,8 A2K' (body-less, standalone): length=1.56
pocket = extrude(sketch_001, amount=-1.56)

result = pocket
