"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Screw_M8x80_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((3.999, 0), (6.5, 0), (6.5, 7.97229))
    + CenterArc(center=(6.47229, 7.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (6.47229, 8), (0, 8), (0, -80), (2.75, -80), (4, -78.75), (4, -52), (3.999, 0)
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (3.498742631289, 0),
    (1.749371315645, 3.03),
    (-1.749371315645, 3.03),
    (-3.498742631289, 0),
    (-1.749371315645, -3.03),
    (1.749371315645, -3.03),
    (3.498742631289, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 8), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M8x80 ISO4762 8,8 A2K' (body-less, standalone): length=6.06
pocket = extrude(sketch_001, amount=-6.06)

result = pocket
