"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Screw_M20x280_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((9.999, 0), (15, 0), (15, 19.97229))
    + CenterArc(center=(14.97229, 19.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (14.97229, 20),
        (0, 20),
        (0, -280),
        (7.5, -280),
        (10, -277.5),
        (10, -228),
        (9.999, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (9.872689603143, 0),
    (4.936344801571, 8.55),
    (-4.936344801571, 8.55),
    (-9.872689603143, 0),
    (-4.936344801571, -8.55),
    (4.936344801571, -8.55),
    (9.872689603143, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 20), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M20x280 ISO4762 8,8 A2K' (body-less, standalone): length=17.1
pocket = extrude(sketch_001, amount=-17.1)

result = pocket
