"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Screw_M24x340_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((11.999, 0), (18, 0), (18, 23.97229))
    + CenterArc(center=(17.97229, 23.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (17.97229, 24),
        (0, 24),
        (0, -340),
        (9, -340),
        (12, -337),
        (12, -280),
        (11.999, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (11.056257654981, 0),
    (5.528128827491, 9.575),
    (-5.528128827491, 9.575),
    (-11.056257654981, 0),
    (-5.528128827491, -9.575),
    (5.528128827491, -9.575),
    (11.056257654981, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 24), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M24x340 ISO4762 8,8 A2K' (body-less, standalone): length=19.15
pocket = extrude(sketch_001, amount=-19.15)

result = pocket
