"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/side-member_top.FCStd."""

from build123d import Edge, Polyline, extrude, fillet, make_face
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 8 lines (2 loops)
sketch_loop_0 = Polyline((-40, 40), (40, 40), (40, -40), (-40, -40), (-40, 40))
sketch_loop_1 = Polyline((-35, 35), (35, 35), (35, -35), (-35, -35), (-35, 35))
sketch = make_face(sketch_loop_0) - make_face(sketch_loop_1)

# PartDesign::Pad 'Pad': length=5707.0
pad = extrude(sketch, amount=2853.5, both=True)

# PartDesign::Fillet 'Fillet': radius=5.0 on 4 edges of Pad
fillet_0 = fillet(
    _edges_at(pad, [(-35, -35, 0), (35, -35, 0), (35, 35, 0), (-35, 35, 0)]), radius=5
)

# PartDesign::Fillet 'Fillet001': radius=10.0 on 4 edges of Fillet
fillet_001 = fillet(
    _edges_at(fillet_0, [(40, 40, 0), (-40, 40, 0), (-40, -40, 0), (40, -40, 0)]),
    radius=10,
)

result = fillet_001
