"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Sprocket_ISO606_simplex_5x2_5_z31.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Circle,
    Plane,
    Polyline,
    Rot,
    Sketch,
    extrude,
    make_face,
    revolve,
)


def _pattern_union(base, *additions):
    """Boolean-union ``base`` with each addition via BuildPart.

    Chained ``+`` on build123d Part objects returns a Compound that does not
    fuse overlapping geometry — so for pattern features whose copies overlap
    (e.g. sprocket teeth meeting at the hub) the resulting volume is wrong.
    Routing through BuildPart.add() invokes OCCT's robust boolean fusion.
    """
    from build123d import BuildPart, add

    with BuildPart() as _bp:
        add(base)
        for s in additions:
            add(s)
    return _bp.part


def make_part(Wt=2.3):
    """Translated parametric design. Defaults match the source values."""
    # Sketcher::SketchObject 'Tooth sketch': 6 lines, 5 arcs (1 loops)
    sketch_profile = (
        CenterArc(
            center=(-2.5000000000000018, 24.58320768329471),
            radius=1.5999999999999994,
            start_angle=275.8067563821446,
            arc_size=84.19324361785544,
        )
        + CenterArc(
            center=(11.771999999999998, 24.58320768329471),
            radius=12.672,
            start_angle=180,
            arc_size=-5.4476136762615965,
        )
        + CenterArc(
            center=(0, 0),
            radius=25.800000000000004,
            start_angle=91.87191926704388,
            arc_size=-3.743838534087743,
        )
        + CenterArc(
            center=(-11.772000000000002, 24.583207683294706),
            radius=12.672,
            start_angle=5.44761367626163,
            arc_size=-5.447613676261619,
        )
        + CenterArc(
            center=(2.4999999999999982, 24.58320768329471),
            radius=1.5999999999999994,
            start_angle=180,
            arc_size=84.19324361785547,
        )
        + Polyline(
            (2.3381222177256156, 22.99141762690978),
            (2.3381222177256156, 0),
            (-2.3381222177256187, 0),
            (-2.3381222177256187, 22.991417626909783),
        )
    )
    sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
        make_face(sketch_profile)
    )

    # PartDesign::Pad 'Tooth': length=Wt
    pad = extrude(sketch, amount=Wt)

    # Sketcher::SketchObject 'Hub sketch': 1 circle (1 loops)
    sketch_002 = Sketch() + Plane(
        origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
    ) * (Circle(15))

    # Sketcher::SketchObject 'Hole sketch': 1 circle (1 loops)
    sketch_003 = Sketch() + Plane(
        origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
    ) * (Circle(4))

    # PartDesign::PolarPattern 'Teeth': PolarPattern around (0, 1, 0), step=11.612903225806452deg, occurrences=31
    polar_pattern = _pattern_union(
        pad,
        Rot(Y=11.612903225806452) * extrude(sketch, amount=Wt),
        Rot(Y=23.225806451612904) * extrude(sketch, amount=Wt),
        Rot(Y=34.83870967741936) * extrude(sketch, amount=Wt),
        Rot(Y=46.45161290322581) * extrude(sketch, amount=Wt),
        Rot(Y=58.064516129032256) * extrude(sketch, amount=Wt),
        Rot(Y=69.67741935483872) * extrude(sketch, amount=Wt),
        Rot(Y=81.29032258064517) * extrude(sketch, amount=Wt),
        Rot(Y=92.90322580645162) * extrude(sketch, amount=Wt),
        Rot(Y=104.51612903225806) * extrude(sketch, amount=Wt),
        Rot(Y=116.12903225806451) * extrude(sketch, amount=Wt),
        Rot(Y=127.74193548387098) * extrude(sketch, amount=Wt),
        Rot(Y=139.35483870967744) * extrude(sketch, amount=Wt),
        Rot(Y=150.96774193548387) * extrude(sketch, amount=Wt),
        Rot(Y=162.58064516129033) * extrude(sketch, amount=Wt),
        Rot(Y=174.19354838709677) * extrude(sketch, amount=Wt),
        Rot(Y=185.80645161290323) * extrude(sketch, amount=Wt),
        Rot(Y=197.4193548387097) * extrude(sketch, amount=Wt),
        Rot(Y=209.03225806451613) * extrude(sketch, amount=Wt),
        Rot(Y=220.6451612903226) * extrude(sketch, amount=Wt),
        Rot(Y=232.25806451612902) * extrude(sketch, amount=Wt),
        Rot(Y=243.8709677419355) * extrude(sketch, amount=Wt),
        Rot(Y=255.48387096774195) * extrude(sketch, amount=Wt),
        Rot(Y=267.0967741935484) * extrude(sketch, amount=Wt),
        Rot(Y=278.7096774193549) * extrude(sketch, amount=Wt),
        Rot(Y=290.3225806451613) * extrude(sketch, amount=Wt),
        Rot(Y=301.93548387096774) * extrude(sketch, amount=Wt),
        Rot(Y=313.5483870967742) * extrude(sketch, amount=Wt),
        Rot(Y=325.16129032258067) * extrude(sketch, amount=Wt),
        Rot(Y=336.77419354838713) * extrude(sketch, amount=Wt),
        Rot(Y=348.38709677419354) * extrude(sketch, amount=Wt),
    )

    # Sketcher::SketchObject 'Radius': 5 lines, 2 arcs (2 loops)
    sketch_001_loop_0 = CenterArc(
        center=(2.7000000000000024, 23.42513158259242),
        radius=5,
        start_angle=151.6423634236721,
        arc_size=28.35799751202194,
    ) + Polyline((-2.3, 23.425100085011174), (-2.3, 25.8), (-1.6999999999999997, 25.8))
    sketch_001_loop_1 = Polyline(
        (-0.6, 25.8), (0, 25.8), (0, 23.425100085011174)
    ) + CenterArc(
        center=(-5, 23.42513158259242),
        radius=5,
        start_angle=359.99963906430594,
        arc_size=28.357997512021996,
    )
    sketch_001 = Sketch() + Plane(
        origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)
    ) * ((make_face(sketch_001_loop_0) + make_face(sketch_001_loop_1)))

    # PartDesign::Groove 'Teeth Radius': angle=-360.0 (reversed)
    groove = polar_pattern - revolve(sketch_001, axis=Axis.Y, revolution_arc=-360)

    # PartDesign::Pad 'Hub': length=15.0
    pad_001 = groove + extrude(sketch_002, amount=15)

    # PartDesign::Pocket 'Hole': ThroughAll (midplane)
    pocket = pad_001 - extrude(sketch_003, amount=500000, both=True)

    return pocket


result = make_part()
