"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Square_Bar_35_EN10059_S235JR.FCStd."""

from build123d import Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline(
    (-17.5, -17.5), (17.5, -17.5), (17.5, 17.5), (-17.5, 17.5), (-17.5, -17.5)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Square Bar 35 EN10059 S235JR': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
