"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Square_hollow_section_80x80x6_3_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-27.4, 33.7), (27.4, 33.7))
    + CenterArc(center=(27.4, 27.4), radius=6.3, start_angle=90, arc_size=-90)
    + Line((33.7, 27.4), (33.7, -27.4))
    + CenterArc(center=(27.4, -27.4), radius=6.3, start_angle=360, arc_size=-90)
    + Line((27.4, -33.7), (-27.4, -33.7))
    + CenterArc(center=(-27.4, -27.4), radius=6.3, start_angle=270, arc_size=-90)
    + Line((-33.7, -27.4), (-33.7, 27.4))
    + CenterArc(center=(-27.4, 27.4), radius=6.3, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-30.55, 40), (30.55, 40))
    + CenterArc(center=(30.55, 30.55), radius=9.45, start_angle=90, arc_size=-90)
    + Line((40, 30.55), (40, -30.55))
    + CenterArc(center=(30.55, -30.55), radius=9.45, start_angle=360, arc_size=-90)
    + Line((30.55, -40), (-30.55, -40))
    + CenterArc(center=(-30.55, -30.55), radius=9.45, start_angle=270, arc_size=-90)
    + Line((-40, -30.55), (-40, 30.55))
    + CenterArc(center=(-30.55, 30.55), radius=9.45, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 80x80x6.3 EN10219 S235JRH': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
