"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Square_hollow_section_80x80x3_2_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-33.6, 36.8), (33.6, 36.8))
    + CenterArc(center=(33.6, 33.6), radius=3.2, start_angle=90, arc_size=-90)
    + Line((36.8, 33.6), (36.8, -33.6))
    + CenterArc(center=(33.6, -33.6), radius=3.2, start_angle=360, arc_size=-90)
    + Line((33.6, -36.8), (-33.6, -36.8))
    + CenterArc(center=(-33.6, -33.6), radius=3.2, start_angle=270, arc_size=-90)
    + Line((-36.8, -33.6), (-36.8, 33.6))
    + CenterArc(center=(-33.6, 33.6), radius=3.2, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-35.2, 40), (35.2, 40))
    + CenterArc(center=(35.2, 35.2), radius=4.8, start_angle=90, arc_size=-90)
    + Line((40, 35.2), (40, -35.2))
    + CenterArc(center=(35.2, -35.2), radius=4.8, start_angle=360, arc_size=-90)
    + Line((35.2, -40), (-35.2, -40))
    + CenterArc(center=(-35.2, -35.2), radius=4.8, start_angle=270, arc_size=-90)
    + Line((-40, -35.2), (-40, 35.2))
    + CenterArc(center=(-35.2, 35.2), radius=4.8, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 80x80x3.2 EN10219 S235JRH': amount=50.0
extrude_0 = extrude(sketch, amount=50)

result = extrude_0
