"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/steel-sheets-3000mm.FCStd."""

from build123d import CenterArc, Line, Plane, Polyline, Sketch, extrude, make_face


def _pattern_difference(base, *removals):
    """Boolean-subtract each removal from ``base`` via BuildPart.

    Mirror of ``_pattern_union`` for subtractive (Pocket Original) patterns.
    Chained ``-`` does *not* exhibit the same Compound-collapsing bug as
    ``+`` in current build123d, but using BuildPart for both keeps the emit
    symmetric and future-proofs against the inverse issue.
    """
    from build123d import BuildPart, Mode, add

    with BuildPart() as _bp:
        add(base)
        for s in removals:
            add(s, mode=Mode.SUBTRACT)
    return _bp.part


# Sketcher::SketchObject 'Sketch': 18 lines, 14 arcs (1 loops)
sketch_profile = (
    Line((0, 2), (8.291853121882, 22.499882238811))
    + CenterArc(
        center=(12, 21),
        radius=4,
        start_angle=157.97750674094345,
        arc_size=-67.97750674093753,
    )
    + Line((12, 25), (39, 25))
    + CenterArc(center=(39, 21), radius=4, start_angle=90, arc_size=-75.95169715177082)
    + Line((42.88036572302, 21.970959245083), (47.11963427698, 5.029040754916998))
    + CenterArc(
        center=(51, 6),
        radius=4,
        start_angle=194.04830284824695,
        arc_size=75.95169715177079,
    )
    + Line((51, 2), (263, 2))
    + CenterArc(center=(263, 6), radius=4, start_angle=270, arc_size=75.95169715177087)
    + Line((266.88036572302, 5.029040754917), (271.11963427698, 21.970959245083))
    + CenterArc(
        center=(275, 21),
        radius=4,
        start_angle=165.95169715177673,
        arc_size=-75.9516971517708,
    )
    + Line((275, 25), (302, 25))
    + CenterArc(center=(302, 21), radius=4, start_angle=90, arc_size=-75.95169715177082)
    + Line((305.88036572302, 21.970959245083), (310.11963427698, 5.029040754916998))
    + CenterArc(
        center=(314, 6),
        radius=4,
        start_angle=194.04830284824695,
        arc_size=75.95169715177079,
    )
    + Line((314, 2), (526, 2))
    + CenterArc(center=(526, 6), radius=4, start_angle=270, arc_size=75.95169715177087)
    + Line((529.88036572302, 5.029040754917), (534.11963427698, 21.970959245083))
    + CenterArc(
        center=(538, 21),
        radius=4,
        start_angle=165.95169715177673,
        arc_size=-75.9516971517708,
    )
    + Line((538, 25), (565, 25))
    + CenterArc(center=(565, 21), radius=4, start_angle=90, arc_size=-75.95169715177082)
    + Line((568.88036572302, 21.970959245083), (573.11963427698, 5.029040754916998))
    + CenterArc(
        center=(577, 6),
        radius=4,
        start_angle=194.04830284824695,
        arc_size=75.95169715177079,
    )
    + Line((577, 2), (789, 2))
    + CenterArc(center=(789, 6), radius=4, start_angle=270, arc_size=75.95169715177087)
    + Line((792.88036572302, 5.029040754917), (797.11963427698, 21.970959245083))
    + CenterArc(
        center=(801, 21),
        radius=4,
        start_angle=165.95169715177673,
        arc_size=-75.9516971517708,
    )
    + Line((801, 25), (828, 25))
    + CenterArc(center=(828, 21), radius=4, start_angle=90, arc_size=-67.97750674099483)
    + Polyline(
        (831.708146878139, 22.499882238806), (840, 2), (840, -2), (0, -2), (0, 2)
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_profile)
)

# PartDesign::Pad 'Pad': length=3000.0
pad = extrude(sketch, amount=3000)

# Sketcher::SketchObject 'Sketch001': 18 lines, 14 arcs (1 loops)
sketch_001_profile = (
    Line((0, 2), (8.291853121882, 22.499882238811))
    + CenterArc(
        center=(12, 21),
        radius=4,
        start_angle=157.97750674094345,
        arc_size=-67.97750674093753,
    )
    + Line((12, 25), (39, 25))
    + CenterArc(center=(39, 21), radius=4, start_angle=90, arc_size=-75.95169715177082)
    + Line((42.88036572302, 21.970959245083), (47.11963427698, 5.029040754916998))
    + CenterArc(
        center=(51, 6),
        radius=4,
        start_angle=194.04830284824695,
        arc_size=75.95169715177079,
    )
    + Line((51, 2), (263, 2))
    + CenterArc(center=(263, 6), radius=4, start_angle=270, arc_size=75.95169715177087)
    + Line((266.88036572302, 5.029040754917), (271.11963427698, 21.970959245083))
    + CenterArc(
        center=(275, 21),
        radius=4,
        start_angle=165.95169715177673,
        arc_size=-75.9516971517708,
    )
    + Line((275, 25), (302, 25))
    + CenterArc(center=(302, 21), radius=4, start_angle=90, arc_size=-75.95169715177082)
    + Line((305.88036572302, 21.970959245083), (310.11963427698, 5.029040754916))
    + CenterArc(
        center=(314, 6),
        radius=4,
        start_angle=194.04830284824695,
        arc_size=75.95169715177079,
    )
    + Line((314, 2), (526, 2))
    + CenterArc(center=(526, 6), radius=4, start_angle=270, arc_size=75.95169715177087)
    + Line((529.88036572302, 5.029040754917), (534.11963427698, 21.970959245083))
    + CenterArc(
        center=(538, 21),
        radius=4,
        start_angle=165.95169715177673,
        arc_size=-75.9516971517708,
    )
    + Line((538, 25), (565, 25))
    + CenterArc(center=(565, 21), radius=4, start_angle=90, arc_size=-75.95169715177082)
    + Line((568.88036572302, 21.970959245083), (573.11963427698, 5.029040754916998))
    + CenterArc(
        center=(577, 6),
        radius=4,
        start_angle=194.04830284824695,
        arc_size=75.95169715177079,
    )
    + Line((577, 2), (789, 2))
    + CenterArc(center=(789, 6), radius=4, start_angle=270, arc_size=75.95169715177087)
    + Line((792.88036572302, 5.029040754917), (797.11963427698, 21.970959245083))
    + CenterArc(
        center=(801, 21),
        radius=4,
        start_angle=165.95169715177673,
        arc_size=-75.9516971517708,
    )
    + Line((801, 25), (828, 25))
    + CenterArc(center=(828, 21), radius=4, start_angle=90, arc_size=-67.97750674099483)
    + Polyline(
        (831.708146878139, 22.499882238806), (840, 2), (840, -2), (0, -2), (0, 2)
    )
)
sketch_001 = Sketch() + Plane(origin=(0, 0, -2), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pad 'Pad001': length=3000.0
pad_001 = pad + extrude(sketch_001, amount=3000)

# Part::Cut 'Cut': Pad - Pad001
cut = _pattern_difference(pad, pad_001)

result = cut
