"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/U_1LooseMax.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=14.9987, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(14.9987, 15)

result = cylinder
