"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/U_5s16LooseMax.FCStd."""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=4.7371, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(4.7371, 15)

result = cylinder
