"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/WallHungBidet.FCStd."""

from build123d import (
    CenterArc,
    Circle,
    Edge,
    Line,
    Plane,
    Polyline,
    Pos,
    Sketch,
    extrude,
    fillet,
    make_face,
)
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 4 lines, 1 arc (1 loops)
sketch_profile = Polyline((0, 350), (0, 0), (350, 0), (350, 350)) + CenterArc(
    center=(175, 350), radius=175, start_angle=0, arc_size=180
)
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=350.0
pad = extrude(sketch, amount=350)

# PartDesign::Fillet 'Fillet': radius=150.0 on 3 edges of Pad
fillet_0 = fillet(
    _edges_at(pad, [(350, 175, 0), (175, 525, 0), (0, 175, 0)]), radius=150
)

# Sketcher::SketchObject 'Sketch001': 3 lines, 1 arc (1 loops)
sketch_001_profile = (
    Polyline((35, 85), (305, 85), (305, 345))
    + CenterArc(center=(170, 345), radius=135, start_angle=0, arc_size=180)
    + Line((35, 345), (35, 85))
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 350), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Pocket': length=200.0
pocket = fillet_0 - extrude(sketch_001, amount=-200)

# Sketcher::SketchObject 'Sketch002': 1 circle (1 loops)
sketch_002 = Sketch() + Plane(origin=(0, 0, 150), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    (Pos(175, 200) * Circle(32))
)

# PartDesign::Pocket 'Pocket001': length=150.0
pocket_001 = pocket - extrude(sketch_002, amount=-150)

# PartDesign::Fillet 'Fillet001': radius=10.0 on 1 edges of Pocket001
fillet_001 = fillet(
    _edges_at(
        pocket_001,
        [
            (0, 175, 350),
            (175, 525, 350),
            (175, 0, 350),
            (350, 175, 350),
            (170, 85, 350),
            (305, 215, 350),
            (170, 480, 350),
            (35, 215, 350),
        ],
    ),
    radius=10,
)

result = fillet_001
