"""Auto-generated by fcstd2b123d from tests/fixtures/sample_813/Winch-Model1-Motor-Cable-Coil.FCStd."""

from build123d import (
    CenterArc,
    Circle,
    Line,
    Plane,
    Polyline,
    Pos,
    Sketch,
    extrude,
    make_face,
)

# Sketcher::SketchObject 'Sketch': 6 lines, 2 arcs (1 loops)
sketch_profile = (
    Polyline((-51, -60.000000734433), (-28, -60.000000734433), (-28, -42.626282971894))
    + CenterArc(
        center=(0, 0),
        radius=51,
        start_angle=236.70022006039363,
        arc_size=66.59955987919102,
    )
    + Polyline(
        (28, -42.626282971894),
        (28, -60.000000734433),
        (51, -60.000000734433),
        (51, -1.9589499800076737e-07),
    )
    + CenterArc(
        center=(0, 0),
        radius=51,
        start_angle=359.9999997799506,
        arc_size=180.00000104514424,
    )
    + Line((-51, -7.344330015257583e-07), (-51, -60.000000734433))
)
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=145.0
pad = extrude(sketch, amount=145)

# Sketcher::SketchObject 'Sketch001': 1 circle (1 loops)
sketch_001 = Sketch() + Plane(origin=(0, 0, 145), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    Circle(38)
)

# PartDesign::Pad 'Pad001': length=95.0
pad_001 = pad + extrude(sketch_001, amount=95)

# Sketcher::SketchObject 'Sketch002': 1 circle (1 loops)
sketch_002 = Sketch() + Plane(origin=(0, 0, 240), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    Circle(34)
)

# PartDesign::Pad 'Pad002': length=7.0
pad_002 = pad_001 + extrude(sketch_002, amount=7)

# Sketcher::SketchObject 'Sketch003': 1 circle (1 loops)
sketch_003 = Sketch() + Plane(origin=(0, 0, 247), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    Circle(32)
)

# PartDesign::Pad 'Pad003': length=14.0
pad_003 = pad_002 + extrude(sketch_003, amount=14)

# Sketcher::SketchObject 'Sketch004': 1 circle (1 loops)
sketch_004 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, -1)) * (
    Circle(48)
)

# PartDesign::Pad 'Pad004': length=17.0
pad_004 = pad_003 + extrude(sketch_004, amount=17)

# Sketcher::SketchObject 'Sketch005': 1 circle (1 loops)
sketch_005 = Sketch() + Plane(origin=(0, 0, -17), x_dir=(1, 0, 0), z_dir=(0, 0, -1)) * (
    Circle(45)
)

# PartDesign::Pad 'Pad005': length=21.0
pad_005 = pad_004 + extrude(sketch_005, amount=21)

# Sketcher::SketchObject 'Sketch006': 1 circle (1 loops)
sketch_006 = Sketch() + Plane(origin=(0, 0, -38), x_dir=(1, 0, 0), z_dir=(0, 0, -1)) * (
    Circle(35)
)

# PartDesign::Pad 'Pad006': length=17.0
pad_006 = pad_005 + extrude(sketch_006, amount=17)

# Sketcher::SketchObject 'Sketch007': 4 lines (1 loops)
sketch_007_profile = Polyline((-51, 114), (51, 114), (51, 31), (-51, 31), (-51, 114))
sketch_007 = Sketch() + Plane(
    origin=(0, -60.00000073443347, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
) * (make_face(sketch_007_profile))

# PartDesign::Pocket 'Pocket' (body-less, chained from PartDesign::Pad): length=5.0
pocket = pad_006 - extrude(sketch_007, amount=-5)

# Sketcher::SketchObject 'Sketch008': 2 circles (2 loops)
sketch_008 = Sketch() + Plane(origin=(0, 0, 31), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    Circle(120) - Circle(20)
)

# PartDesign::Pocket 'Pocket001' (body-less, chained from PartDesign::Pocket): length=84.0 (reversed)
pocket_001 = pocket - extrude(sketch_008, amount=84)

# Sketcher::SketchObject 'Sketch009': 4 circles (4 loops)
sketch_009 = Sketch() + Plane(
    origin=(0, -60.00000073443347, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
) * (
    (
        (Pos(-38.5, 132) * Circle(4))
        + (Pos(38.5, 132) * Circle(4))
        + (Pos(-38.5, 12) * Circle(4))
        + (Pos(38.5, 12) * Circle(4))
    )
)

# PartDesign::Pocket 'Pocket002' (body-less, chained from PartDesign::Pocket): length=10.0
pocket_002 = pocket_001 - extrude(sketch_009, amount=-10)

result = pocket_002
