"""Code-emission primitives: TranslationUnit and the module renderer.

Pure Python — does not import FreeCAD or build123d. The translator's job is
to produce TranslationUnits; the emitter's job is to format them into a
clean .py source.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


def format_value(v: float) -> str:
    """Render a float as a compact, LLM-friendly literal.

    Snaps FP-roundoff noise: ``-19.999999999993534`` (diff 6e-12 from -20)
    becomes ``-20``. Genuinely-imprecise computed values stay verbatim —
    e.g. an arc's start_angle reported as ``270.000035`` is a *real*
    computed angle that landed near 270° to satisfy other sketch
    constraints. Snapping it would shift the arc's endpoint by ~50 µm and
    break the closed-wire continuity build123d's make_face requires.

    So: snap only when the difference from the nearest integer is at the
    scale of double-precision rounding error (≤ 1e-9 absolute, or 1e-12
    relative for very large magnitudes).
    """
    if abs(v) < 1e-12:
        return "0"
    nearest = round(v)
    # Conservative: FP roundoff is typically ~1e-12 relative.
    tol = max(1e-9, abs(v) * 1e-12)
    if abs(v - nearest) < tol:
        return f"{int(nearest)}"
    return repr(v)


def vfmt(*values) -> str:
    """Comma-join formatted floats (used in primitive constructor emits)."""
    return ", ".join(format_value(v) for v in values)


# Module-level helpers emitted at the top of the generated source when
# referenced. Keyed by name in TranslationUnit.helpers. Definitions live
# here so the same helper is emitted at most once per module.
HELPER_DEFINITIONS = {
    "_edges_at": """def _edges_at(shape, points, tol=1e-3):
    \"\"\"Select edges whose midpoints match any of the target points.

    Used by translated Fillet / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    \"\"\"
    from build123d import Vector
    targets = [Vector(*p) for p in points]
    return [
        e for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]""",
}


@dataclass
class TranslationUnit:
    """One translated FreeCAD object.

    Attributes:
        var_name: a valid Python identifier the emitter assigns the result to.
        imports: build123d names to import (e.g. {"Box", "Pos"}).
        lines: the executable statement(s). Conventionally a single assignment
            to ``var_name``, but may include intermediate locals when needed.
        comment: a one-line provenance comment placed above the lines.
        helpers: names of module-level helpers required (see HELPER_DEFINITIONS).
    """

    var_name: str
    imports: set[str] = field(default_factory=set)
    lines: list[str] = field(default_factory=list)
    comment: str = ""
    helpers: set[str] = field(default_factory=set)


def render_module(units: list[TranslationUnit], source_path: Path | str) -> str:
    """Render translation units into a complete build123d Python module.

    The last unit's ``var_name`` is also aliased to ``result`` so callers
    (and the test harness) have a stable name for the translated geometry.

    Output is piped through black so emitted source is consistently
    formatted regardless of how individual translators construct strings.
    """
    if not units:
        raise ValueError("No translation units to render.")

    imports: set[str] = set()
    helpers: set[str] = set()
    for u in units:
        imports.update(u.imports)
        helpers.update(u.helpers)
    import_line = f"from build123d import {', '.join(sorted(imports))}"

    body_lines: list[str] = []
    for u in units:
        if u.comment:
            body_lines.append(f"# {u.comment}")
        body_lines.extend(u.lines)
        body_lines.append("")

    helper_block = ""
    if helpers:
        helper_block = "\n\n".join(
            HELPER_DEFINITIONS[h] for h in sorted(helpers) if h in HELPER_DEFINITIONS
        ) + "\n\n"

    final_var = units[-1].var_name

    raw = (
        f'"""Auto-generated by fcstd2b123d from {source_path}."""\n'
        f"{import_line}\n"
        f"\n"
        + helper_block
        + "\n".join(body_lines)
        + f"\nresult = {final_var}\n"
    )
    return _format(raw)


def _format(source: str) -> str:
    import black

    return black.format_str(source, mode=black.FileMode())
