"""Code-emission primitives: TranslationUnit and the module renderer.

Pure Python — does not import FreeCAD or build123d. The translator's job is
to produce TranslationUnits; the emitter's job is to format them into a
clean .py source.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class TranslationUnit:
    """One translated FreeCAD object.

    Attributes:
        var_name: a valid Python identifier the emitter assigns the result to.
        imports: build123d names to import (e.g. {"Box", "Pos"}).
        lines: the executable statement(s). Conventionally a single assignment
            to ``var_name``, but may include intermediate locals when needed.
        comment: a one-line provenance comment placed above the lines.
    """

    var_name: str
    imports: set[str] = field(default_factory=set)
    lines: list[str] = field(default_factory=list)
    comment: str = ""


def render_module(units: list[TranslationUnit], source_path: Path | str) -> str:
    """Render translation units into a complete build123d Python module.

    The last unit's ``var_name`` is also aliased to ``result`` so callers
    (and the test harness) have a stable name for the translated geometry.
    """
    if not units:
        raise ValueError("No translation units to render.")

    imports: set[str] = set()
    for u in units:
        imports.update(u.imports)
    import_line = f"from build123d import {', '.join(sorted(imports))}"

    body_lines: list[str] = []
    for u in units:
        if u.comment:
            body_lines.append(f"# {u.comment}")
        body_lines.extend(u.lines)
        body_lines.append("")

    final_var = units[-1].var_name

    return (
        f'"""Auto-generated by fcstd2b123d from {source_path}."""\n'
        f"{import_line}\n"
        f"\n"
        + "\n".join(body_lines)
        + f"\nresult = {final_var}\n"
    )
