"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Angle_Bar_130x90x10_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (130, 0), (130, 5))
    + CenterArc(center=(125, 5), radius=5, start_angle=0, arc_size=90)
    + Line((125, 10), (21, 10))
    + CenterArc(center=(21, 21), radius=11, start_angle=270, arc_size=-90)
    + Line((10, 21), (10, 85))
    + CenterArc(center=(5, 85), radius=5, start_angle=0, arc_size=90)
    + Polyline((5, 90), (0, 90), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar 130x90x10 EN10056 S235JR': amount=50.0
angle_bar_130x90x10_en10056_s235jr = extrude(sketch, amount=50)

result = angle_bar_130x90x10_en10056_s235jr
