"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Angle_Bar_L140x140x10_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (140, 0), (140, 2.5))
    + CenterArc(center=(132.5, 2.5), radius=7.5, start_angle=0, arc_size=90)
    + Line((132.49999999999923, 10), (25, 10))
    + CenterArc(center=(25, 25), radius=15, start_angle=270, arc_size=-90)
    + Line((10, 25), (10, 132.5))
    + CenterArc(center=(2.5, 132.5), radius=7.5, start_angle=0, arc_size=90)
    + Polyline((2.4999999999982254, 140), (0, 140), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar L140x140x10 EN10056 S235JR': amount=50.0
angle_bar_l140x140x10_en10056_s235jr = extrude(sketch, amount=50)

result = angle_bar_l140x140x10_en10056_s235jr
