"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Angle_Bar_L35x35x3_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (35, 0), (35, 0.5))
    + CenterArc(center=(32.5, 0.5), radius=2.5, start_angle=0, arc_size=90)
    + Line((32.499999999999744, 3), (8, 3))
    + CenterArc(center=(8, 8), radius=5, start_angle=270, arc_size=-90)
    + Line((3, 8), (3, 32.5))
    + CenterArc(center=(0.5, 32.5), radius=2.5, start_angle=0, arc_size=90)
    + Polyline((0.4999999999997415, 35), (0, 35), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar L35x35x3 EN10056 S235JR': amount=50.0
angle_bar_l35x35x3_en10056_s235jr = extrude(sketch, amount=50)

result = angle_bar_l35x35x3_en10056_s235jr
