"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Angle_Bar_70x50x5_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (70, 0), (70, 2))
    + CenterArc(center=(67, 2), radius=3, start_angle=0, arc_size=90)
    + Line((67, 5), (11, 5))
    + CenterArc(center=(11, 11), radius=6, start_angle=270, arc_size=-90)
    + Line((5, 11), (5, 47))
    + CenterArc(center=(2, 47), radius=3, start_angle=0, arc_size=90)
    + Polyline((2, 50), (0, 50), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar 70x50x5 EN10056 S235JR': amount=50.0
angle_bar_70x50x5_en10056_s235jr = extrude(sketch, amount=50)

result = angle_bar_70x50x5_en10056_s235jr
