"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Angle_Bar_45x30x3_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (45, 0), (45, 1))
    + CenterArc(center=(43, 1), radius=2, start_angle=0, arc_size=90)
    + Line((43, 3), (7.500000000001393, 3))
    + CenterArc(center=(7.5, 7.5), radius=4.5, start_angle=270, arc_size=-90)
    + Line((3, 7.5), (3, 28))
    + CenterArc(center=(1, 28), radius=2, start_angle=0, arc_size=90)
    + Polyline((1, 30), (0, 30), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar 45x30x3 EN10056 S235JR': amount=50.0
angle_bar_45x30x3_en10056_s235jr = extrude(sketch, amount=50)

result = angle_bar_45x30x3_en10056_s235jr
