"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Angle_Bar_L70x70x7_EN10056_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 6 lines, 3 arcs (1 loops)
sketch_profile = (
    Polyline((0, 0), (70, 0), (70, 2))
    + CenterArc(center=(65, 2), radius=5, start_angle=0, arc_size=90)
    + Line((65, 7), (17, 7))
    + CenterArc(center=(17, 17), radius=10, start_angle=270, arc_size=-90)
    + Line((7, 17), (7, 65))
    + CenterArc(center=(2, 65), radius=5, start_angle=0, arc_size=90)
    + Polyline((2, 70), (0, 70), (0, 0))
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'Angle Bar L70x70x7 EN10056 S235JR': amount=50.0
angle_bar_l70x70x7_en10056_s235jr = extrude(sketch, amount=50)

result = angle_bar_l70x70x7_en10056_s235jr
