"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Caisson.FCStd."""

from build123d import Axis, Plane, Polyline, Sketch, make_face, revolve

# Sketcher::SketchObject 'Caisson_dimensions': 7 lines (1 loops)
caisson_dimensions_profile = Polyline(
    (0, 0), (500, 0), (500, -3250), (1500, -4800), (1500, -5000), (0, -5000), (0, 0)
)
caisson_dimensions = Sketch() + Plane(
    origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
) * (make_face(caisson_dimensions_profile))

# PartDesign::Revolution 'Caisson ': angle=-360.0 (reversed)
caisson = revolve(caisson_dimensions, axis=Axis.Z, revolution_arc=-360)

result = caisson
