"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/ComputerDesk__100_x_50_x_75_cm_WDH_.FCStd."""

from build123d import (
    Axis,
    Circle,
    Plane,
    Polyline,
    Pos,
    Rot,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 4 lines, 1 circle (2 loops)
sketch_profile = Polyline(
    (-500, 250), (-500, -250), (500, -250), (500, 250), (-500, 250)
)
sketch = make_face(sketch_profile) - (Pos(420, 170) * Circle(30))

# PartDesign::Pad 'Pad': length=15.0
pad = extrude(sketch, amount=15)

# Body Placement: base=(0.0, 14.0, 499.0), rotation angle=0.000°
toppannel = Pos(0, 14, 499) * pad

# Sketcher::SketchObject 'Sketch001': 4 lines (1 loops)
sketch_001_profile = Polyline(
    (-225, 375), (-225, -375), (225, -375), (225, 375), (-225, 375)
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pad 'Pad001': length=15.0
pad_001 = extrude(sketch_001, amount=15)

# Body Placement: base=(-500.0, 25.0, 124.0), rotation angle=0.000°
leftpannel = Pos(-500, 25, 124) * pad_001

# Sketcher::SketchObject 'Sketch002': 4 lines (1 loops)
sketch_002_profile = Polyline(
    (-225, 375), (-225, -375), (225, -375), (225, 375), (-225, 375)
)
sketch_002 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_002_profile)
)

# PartDesign::Pad 'Pad002': length=15.0
pad_002 = extrude(sketch_002, amount=15)

# Body Placement: base=(483.0, 24.0, 124.0), rotation angle=0.000°
rightpannel = Pos(483, 24, 124) * pad_002

# Sketcher::SketchObject 'Sketch003': 4 lines, 1 circle (2 loops)
sketch_003_profile = Polyline(
    (-225, 375), (-225, -375), (225, -375), (225, 375), (-225, 375)
)
sketch_003 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_003_profile) - (Pos(145, 295) * Circle(30))
)

# PartDesign::Pad 'Pad003': length=15.0
pad_003 = extrude(sketch_003, amount=15)

# Body Placement: base=(-202.0, 23.0, 123.0), rotation angle=0.000°
middlepnnel = Pos(-202, 23, 123) * pad_003

# Sketcher::SketchObject 'Sketch004': 4 lines (1 loops)
sketch_004_profile = Polyline(
    (-500, 150), (-500, -150), (500, -150), (500, 150), (-500, 150)
)
sketch_004 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_004_profile)
)

# PartDesign::Pad 'Pad004': length=15.0
pad_004 = extrude(sketch_004, amount=15)

# Body Placement: base=(0.0, 265.0, 348.0), rotation angle=0.000°
rearpannel = Pos(0, 265, 348) * pad_004

# Sketcher::SketchObject 'Sketch005': 4 lines (1 loops)
sketch_005_profile = Polyline(
    (-145, 225), (-145, -225), (145, -225), (145, 225), (-145, 225)
)
sketch_005 = make_face(sketch_005_profile)

# PartDesign::Pad 'Pad005': length=15.0
pad_005 = extrude(sketch_005, amount=15)

# Body Placement: base=(-340.0, 26.0, -204.0), rotation angle=0.000°
bottompannel = Pos(-340, 26, -204) * pad_005

# Sketcher::SketchObject 'Sketch006': 4 lines (1 loops)
sketch_006_profile = Polyline(
    (-335, 225), (-335, -225), (335, -225), (335, 225), (-335, 225)
)
sketch_006 = make_face(sketch_006_profile)

# PartDesign::Pad 'Pad006': length=15.0
pad_006 = extrude(sketch_006, amount=15)

# Body Placement: base=(147.0, -99.0, 340.0), rotation angle=0.000°
keyboardpannel = Pos(147, -99, 340) * pad_006

# Sketcher::SketchObject 'Sketch007': 8 lines (1 loops)
sketch_007_profile = Polyline(
    (25, 12.5),
    (25, -12.5),
    (35, -12.5),
    (40, -7.5),
    (30, -7.5),
    (30, 7.5),
    (40, 7.5),
    (35, 12.5),
    (25, 12.5),
)
sketch_007 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)) * (
    make_face(sketch_007_profile)
)

# PartDesign::Revolution 'Revolution': angle=-360.0 (reversed)
revolution = revolve(sketch_007, axis=Axis.Z, revolution_arc=-360)

# Body Placement: base=(420.0, 184.0, 507.0), rotation angle=0.000°
cablemanagementtop = Pos(420, 184, 507) * revolution

# PartDesign::Revolution 'Revolution001': angle=-360.0 (reversed)
revolution_001 = revolve(sketch_007, axis=Axis.Z, revolution_arc=-360)

# Body Placement: base=(-193.38880031708234, 167.7066541124226, 418.0000000000001), rotation angle=90.000°
cablemanagementmiddle = (
    Pos(-193.38880031708234, 167.7066541124226, 418) * Rot(Y=90) * revolution_001
)

result = cablemanagementmiddle
