"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/DIN463_M14TabWasher.FCStd."""

from build123d import CenterArc, Circle, Edge, Polyline, extrude, fillet, make_face
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 6 lines, 2 arcs, 1 circle (2 loops)
sketch_profile = (
    Polyline((-12.64911064067611, -6), (-28, -6), (-28, 6), (-12.649110640675067, 6))
    + CenterArc(
        center=(0, 0),
        radius=14,
        start_angle=514.6230664748625,
        arc_size=-219.2461329497291,
    )
    + Polyline((6, -12.649110640675492), (6, -16), (-6, -16), (-6, -12.649110640673209))
    + CenterArc(
        center=(0, 0),
        radius=14,
        start_angle=244.62306647484476,
        arc_size=-39.24613294971721,
    )
)
sketch = make_face(sketch_profile) - Circle(7.5)

# PartDesign::Pad 'Pad': length=1.0
pad = extrude(sketch, amount=1)

# PartDesign::Fillet 'Fillet': radius=6.0 on 1 edges of Pad
fillet_0 = fillet(_edges_at(pad, [(-12.649110640673523, 6, 0.5)]), radius=6)

# PartDesign::Fillet 'Fillet001': radius=1.0 on 1 edges of Fillet
fillet_001 = fillet(_edges_at(fillet_0, [(6, -12.649110640673522, 0.5)]), radius=1)

result = fillet_001
