"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Flat_Bar_80x5_EN10058_S235JR.FCStd."""

from build123d import Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline((-40, -2.5), (40, -2.5), (40, 2.5), (-40, 2.5), (-40, -2.5))
sketch = make_face(sketch_profile)

# Part::Extrusion 'Flat Bar 80x5 EN10058 S235JR': amount=50.0
flat_bar_80x5_en10058_s235jr = extrude(sketch, amount=50)

result = flat_bar_80x5_en10058_s235jr
