"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Flat_Bar_60x4_EN10058_S235JR.FCStd."""

from build123d import Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline((-30, -2), (30, -2), (30, 2), (-30, 2), (-30, -2))
sketch = make_face(sketch_profile)

# Part::Extrusion 'Flat Bar 60x4 EN10058 S235JR': amount=50.0
flat_bar_60x4_en10058_s235jr = extrude(sketch, amount=50)

result = flat_bar_60x4_en10058_s235jr
