"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/front-member_vertical-2_mir.FCStd."""

from build123d import (
    Edge,
    Locations,
    Plane,
    Polyline,
    Sketch,
    extrude,
    fillet,
    make_face,
)
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 10 lines (1 loops)
sketch_profile = Polyline(
    (0, 42),
    (0, 0),
    (-169.5, 0),
    (-169.5, 45),
    (-209.5, 45),
    (-209.5, 48),
    (-166.5, 48),
    (-166.5, 3),
    (-3, 3),
    (-3, 42),
    (0, 42),
)
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=2353.0
pad = extrude(sketch, amount=2353)

# PartDesign::Fillet 'Fillet': radius=3.0 on 3 edges of Pad
fillet_0 = fillet(
    _edges_at(pad, [(-166.5, 3, 1176.5), (-3, 3, 1176.5), (-169.5, 45, 1176.5)]),
    radius=3,
)

# PartDesign::Fillet 'Fillet001': radius=6.0 on 3 edges of Fillet
fillet_001 = fillet(
    _edges_at(fillet_0, [(-169.5, 0, 1176.5), (0, 0, 1176.5), (-166.5, 48, 1176.5)]),
    radius=6,
)

# Sketcher::SketchObject 'Sketch001': 4 lines (1 loops)
sketch_001_profile = Polyline(
    (166.5, 2353), (266.5, 2353), (266.5, 2297), (166.5, 2297), (166.5, 2353)
)
sketch_001 = Sketch() + Plane(origin=(0, 48, 0), x_dir=(-1, 0, 0), z_dir=(0, 1, 0)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Pocket': length=6.0
pocket = fillet_001 - extrude(sketch_001, amount=-6)

# Sketcher::SketchObject 'Sketch002': 4 lines (1 loops)
sketch_002_profile = Polyline(
    (-166.5, 42), (-169.5, 42), (-169.5, 64), (-166.5, 64), (-166.5, 42)
)
sketch_002 = Sketch() + Plane(origin=(0, 0, 2297), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_002_profile)
)

# PartDesign::Pad 'Pad001': length=56.0
pad_001 = pocket + extrude(sketch_002, amount=56)

# PartDesign::Fillet 'Fillet002': radius=6.0 on 1 edges of Pad001
fillet_002 = fillet(_edges_at(pad_001, [(-168, 64, 2297)]), radius=6)

# Sketcher::SketchObject 'Sketch003': 4 lines (1 loops)
sketch_003_profile = Polyline((0, 140), (50, 140), (50, 260), (0, 260), (0, 140))
sketch_003 = Sketch() + Plane(origin=(0, 42, 0), x_dir=(-1, 0, 0), z_dir=(0, 1, 0)) * (
    make_face(sketch_003_profile)
)

# PartDesign::Pocket 'Pocket001': ThroughAll
pocket_001 = fillet_002 - extrude(sketch_003, amount=-1000000)

# PartDesign::LinearPattern 'LinearPattern': LinearPattern along (0, 0, 1), step=976.5, occurrences=3
linear_pattern = pocket_001 - Locations((0, 0, 976.5), (0, 0, 1953)) * extrude(
    sketch_003, amount=-1000000
)

result = linear_pattern
