"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/front-member_vertical.FCStd."""

from build123d import Edge, Polyline, extrude, fillet, make_face
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / Chamfer features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 6 lines (1 loops)
sketch_profile = Polyline(
    (0, 0), (45, 0), (45, 3), (3, 3), (3, 97.5), (0, 97.5), (0, 0)
)
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=2302.0
pad = extrude(sketch, amount=1151, both=True)

# PartDesign::Fillet 'Fillet': radius=3.0 on 1 edges of Pad
fillet_0 = fillet(_edges_at(pad, [(3, 3, 0)]), radius=3)

# PartDesign::Fillet 'Fillet001': radius=6.0 on 1 edges of Fillet
fillet_001 = fillet(_edges_at(fillet_0, [(0, 0, 0)]), radius=6)

result = fillet_001
