"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/HE-A-Profile_550_DIN1025-3_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 12 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((6.25, -219), (6.25, 219))
    + CenterArc(center=(33.25, 219), radius=27, start_angle=180, arc_size=-90)
    + Polyline(
        (33.25, 246),
        (150, 246),
        (150, 270),
        (-150, 270),
        (-150, 246),
        (-33.250000000002785, 246),
    )
    + CenterArc(center=(-33.25, 219), radius=27, start_angle=90, arc_size=-90)
    + Line((-6.25, 219), (-6.25, -219))
    + CenterArc(center=(-33.25, -219), radius=27, start_angle=360, arc_size=-90)
    + Polyline(
        (-33.25000000000001, -246),
        (-150, -246),
        (-150, -270),
        (150, -270),
        (150, -246),
        (33.250000000008356, -246),
    )
    + CenterArc(center=(33.25, -219), radius=27, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'HE-A-Profile 550 DIN1025-3 S235JR': amount=50.0
he_a_profile_550_din1025_3_s235jr = extrude(sketch, amount=50)

result = he_a_profile_550_din1025_3_s235jr
