"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/HE-A-Profile_260_DIN1025-3_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 12 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((3.75, -88.5), (3.75, 88.49999999999505))
    + CenterArc(center=(27.75, 88.5), radius=24, start_angle=180, arc_size=-90)
    + Polyline(
        (27.75, 112.5),
        (130, 112.5),
        (130, 125),
        (-130, 125),
        (-130, 112.5),
        (-27.750000000002487, 112.5),
    )
    + CenterArc(center=(-27.75, 88.5), radius=24, start_angle=90, arc_size=-90)
    + Line((-3.75, 88.5), (-3.75, -88.49999999999005))
    + CenterArc(center=(-27.75, -88.5), radius=24, start_angle=360, arc_size=-90)
    + Polyline(
        (-27.750000000000004, -112.5),
        (-130, -112.5),
        (-130, -125),
        (130, -125),
        (130, -112.5),
        (27.750000000007432, -112.5),
    )
    + CenterArc(center=(27.75, -88.5), radius=24, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'HE-A-Profile 260 DIN1025-3 S235JR': amount=50.0
he_a_profile_260_din1025_3_s235jr = extrude(sketch, amount=50)

result = he_a_profile_260_din1025_3_s235jr
