"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/HE-B-Profile_320_DIN1025-2_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 12 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((5.75, -112.5), (5.75, 112.49999999999443))
    + CenterArc(center=(32.75, 112.5), radius=27, start_angle=180, arc_size=-90)
    + Polyline(
        (32.75, 139.5),
        (150, 139.5),
        (150, 160),
        (-150, 160),
        (-150, 139.5),
        (-32.750000000002785, 139.5),
    )
    + CenterArc(center=(-32.75, 112.5), radius=27, start_angle=90, arc_size=-90)
    + Line((-5.75, 112.5), (-5.75, -112.49999999998883))
    + CenterArc(center=(-32.75, -112.5), radius=27, start_angle=360, arc_size=-90)
    + Polyline(
        (-32.75000000000001, -139.5),
        (-150, -139.5),
        (-150, -160),
        (150, -160),
        (150, -139.5),
        (32.750000000008356, -139.5),
    )
    + CenterArc(center=(32.75, -112.5), radius=27, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'HE-B-Profile 320 DIN1025-2 S235JR': amount=50.0
he_b_profile_320_din1025_2_s235jr = extrude(sketch, amount=50)

result = he_b_profile_320_din1025_2_s235jr
