"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/HE-M-Profile_200_DIN1025-4_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 12 lines, 4 arcs (1 loops)
sketch_profile = (
    Line((7.5, -67), (7.5, 67))
    + CenterArc(center=(25.5, 67), radius=18, start_angle=180, arc_size=-90)
    + Polyline(
        (25.5, 85),
        (103, 85),
        (103, 110),
        (-103, 110),
        (-103, 85),
        (-25.500000000028862, 85),
    )
    + CenterArc(center=(-25.5, 67), radius=18, start_angle=90, arc_size=-90)
    + Line((-7.5, 67), (-7.5, -67))
    + CenterArc(center=(-25.5, -67), radius=18, start_angle=360, arc_size=-90)
    + Polyline(
        (-25.500000000000004, -85),
        (-103, -85),
        (-103, -110),
        (103, -110),
        (103, -85),
        (25.500000000031577, -85),
    )
    + CenterArc(center=(25.5, -67), radius=18, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'HE-M-Profile 200 DIN1025-4 S235JR': amount=50.0
he_m_profile_200_din1025_4_s235jr = extrude(sketch, amount=50)

result = he_m_profile_200_din1025_4_s235jr
