"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/housing-2-54mm-2p.FCStd."""

from build123d import Edge, Plane, Polyline, Sketch, chamfer, extrude, make_face
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated Fillet / chamfer_0 features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


def _pattern_union(base, *additions):
    """Boolean-union ``base`` with each addition via BuildPart.

    Chained ``+`` on build123d Part objects returns a Compound that does not
    fuse overlapping geometry — so for pattern features whose copies overlap
    (e.g. sprocket teeth meeting at the hub) the resulting volume is wrong.
    Routing through BuildPart.add() invokes OCCT's robust boolean fusion.
    """
    from build123d import BuildPart, add

    with BuildPart() as _bp:
        add(base)
        for s in additions:
            add(s)
    return _bp.part


# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline((0, 0), (7.5, 0), (7.5, -5.6), (0, -5.6), (0, 0))
sketch = make_face(sketch_profile)

# PartDesign::Pad 'Pad': length=7.0
pad = extrude(sketch, amount=7)

# Sketcher::SketchObject 'Sketch001': 4 lines (1 loops)
sketch_001_profile = Polyline(
    (6.7, -4.8),
    (0.7999999999999998, -4.8),
    (0.8, -0.7999999999999998),
    (6.7, -0.8),
    (6.7, -4.8),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 7), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Pocket' (body-less, chained from PartDesign::Pad): length=5.5
pocket = pad - extrude(sketch_001, amount=-5.5)

# Sketcher::SketchObject 'Sketch002': 4 lines (1 loops)
sketch_002_profile = Polyline((0, -0.8), (7.5, -0.8), (7.5, -1.6), (0, -1.6), (0, -0.8))
sketch_002 = Sketch() + Plane(origin=(0, 0, 7), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_002_profile)
)

# PartDesign::Pocket 'Pocket001' (body-less, chained from PartDesign::Pocket): length=2.0
pocket_001 = pocket - extrude(sketch_002, amount=-2)

# Sketcher::SketchObject 'Sketch003': 4 lines (1 loops)
sketch_003_profile = Polyline((2, 0), (5.5, 0), (5.5, -0.8), (2, -0.8), (2, 0))
sketch_003 = Sketch() + Plane(origin=(0, 0, 7), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_003_profile)
)

# PartDesign::Pocket 'Pocket002' (body-less, chained from PartDesign::Pocket): length=3.0
pocket_002 = pocket_001 - extrude(sketch_003, amount=-3)

# Sketcher::SketchObject 'Sketch004': 11 lines (2 loops)
sketch_004_loop_0 = Polyline(
    (2.23, -2.04), (2.73, -2.04), (2.73, -2.54), (2.23, -2.54), (2.23, -2.04)
)
sketch_004_loop_1 = Polyline(
    (4.77, -2.04), (5.27, -2.04), (5.27, -2.54), (4.77, -2.54), (4.77, -2.04)
)
sketch_004 = Sketch() + Plane(origin=(0, 0, 1.5), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    (make_face(sketch_004_loop_0) + make_face(sketch_004_loop_1))
)

# PartDesign::Pad 'Pad001': TwoLengths fwd=5.5 bwd=4.5
pad_001 = _pattern_union(
    pocket_002, extrude(sketch_004, amount=5.5), extrude(sketch_004, amount=-4.5)
)

# PartDesign::Chamfer 'Chamfer': size=0.1 on 16 edges of Pad001
chamfer_0 = chamfer(
    _edges_at(
        pad_001,
        [
            (5.02, -2.04, 7),
            (5.27, -2.29, 7),
            (5.02, -2.54, 7),
            (4.77, -2.29, 7),
            (2.48, -2.04, 7),
            (2.73, -2.29, 7),
            (2.48, -2.54, 7),
            (2.23, -2.29, 7),
            (2.48, -2.04, -3),
            (2.73, -2.29, -3),
            (2.48, -2.54, -3),
            (2.23, -2.29, -3),
            (5.02, -2.04, -3),
            (5.27, -2.29, -3),
            (5.02, -2.54, -3),
            (4.77, -2.29, -3),
        ],
    ),
    length=0.1,
)

result = chamfer_0
