"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/IgnusNutMount.FCStd."""

from build123d import (
    Circle,
    Edge,
    Plane,
    Polyline,
    Pos,
    Sketch,
    chamfer,
    extrude,
    fillet,
    make_face,
)
from typing import Any


def _edges_at(
    shape: Any,
    points: list[tuple[float, float, float]],
    tol: float = 1e-3,
) -> list[Edge]:
    """Select edges whose midpoints match any of the target points.

    Used by translated fillet_0 / chamfer_0 features — FreeCAD references edges
    by index, the translator captures their world-frame midpoints from
    FreeCAD's evaluated BRep, and this helper finds the corresponding
    edges in build123d's BRep.
    """
    from build123d import Vector

    targets = [Vector(*p) for p in points]
    return [
        e
        for e in shape.edges()
        if any((e.position_at(0.5) - t).length < tol for t in targets)
    ]


# Sketcher::SketchObject 'Sketch': 2 lines, 3 circles (3 loops)
sketch = Circle(22.5) - (Pos(0, 17) * Circle(2)) - (Pos(0, -17) * Circle(2))

# PartDesign::Pad 'Pad': length=10.0
pad = extrude(sketch, amount=10)

# Sketcher::SketchObject 'Sketch001': 4 lines (1 loops)
sketch_001_profile = Polyline((-19, 10), (19, 10), (19, -10), (-19, -10), (-19, 10))
sketch_001 = make_face(sketch_001_profile)

# PartDesign::Pad 'Pad001': length=30.0
pad_001 = pad + extrude(sketch_001, amount=30)

# Sketcher::SketchObject 'Sketch002': 1 circle (1 loops)
sketch_002 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    (Pos(0, 20) * Circle(5))
)

# PartDesign::Pad 'Pad002': length=50.0
pad_002 = pad_001 + extrude(sketch_002, amount=25, both=True)

# Sketcher::SketchObject 'Sketch003': 1 circle (1 loops)
sketch_003 = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    (Pos(0, 20) * Circle(2))
)

# PartDesign::Pocket 'Pocket': length=50.0 (midplane)
pocket = pad_002 - extrude(sketch_003, amount=25, both=True)

# Sketcher::SketchObject 'Sketch004': 1 circle (1 loops)
sketch_004 = Circle(5)

# PartDesign::Pocket 'Pocket001': ThroughAll (reversed)
pocket_001 = pocket - extrude(sketch_004, amount=1000000)

# Sketcher::SketchObject 'Sketch005': 8 lines (2 loops)
sketch_005_loop_0 = Polyline((-14, 25), (14, 25), (14, -25), (-14, -25), (-14, 25))
sketch_005_loop_1 = Polyline((-40, 40), (40, 40), (40, -40), (-40, -40), (-40, 40))
sketch_005 = make_face(sketch_005_loop_1) - make_face(sketch_005_loop_0)

# PartDesign::Pocket 'Pocket002': length=10.0 (reversed)
pocket_002 = pocket_001 - extrude(sketch_005, amount=10)

# PartDesign::Fillet 'Fillet': radius=4.5 on 2 edges of Pocket002
fillet_0 = fillet(_edges_at(pocket_002, [(-14, 0, 10), (14, 0, 10)]), radius=4.5)

# PartDesign::Fillet 'Fillet001': radius=3.0 on 4 edges of Fillet
fillet_001 = fillet(
    _edges_at(
        fillet_0, [(14, -10, 7.75), (14, 10, 7.75), (-14, 10, 7.75), (-14, -10, 7.75)]
    ),
    radius=3,
)

# PartDesign::Fillet 'Fillet002': radius=3.0 on 2 edges of Fillet001
fillet_002 = fillet(_edges_at(fillet_001, [(0, 10, 10), (0, -10, 10)]), radius=3)

# PartDesign::Fillet 'Fillet003': radius=3.0 on 2 edges of Fillet002
fillet_003 = fillet(_edges_at(fillet_002, [(5, 0, 9), (-25, -5, 20)]), radius=3)

# PartDesign::Fillet 'Fillet004': radius=2.0 on 2 edges of Fillet003
fillet_004 = fillet(_edges_at(fillet_003, [(0, -10, 30), (0, 10, 30)]), radius=2)

# PartDesign::Fillet 'Fillet005': radius=1.0 on 2 edges of Fillet004
fillet_005 = fillet(
    _edges_at(
        fillet_004,
        [
            (-14.62433912369843, -11.167996870819854, 7.786755965961233),
            (14.624338977418487, -11.16799707185452, 7.786755707332024),
        ],
    ),
    radius=1,
)

# PartDesign::Chamfer 'Chamfer': size=2.0 on 2 edges of Fillet005
chamfer_0 = chamfer(_edges_at(fillet_005, [(-2, -17, 0), (-2, 17, 0)]), length=2)

# PartDesign::Fillet 'Fillet006': radius=2.0 on 4 edges of Chamfer
fillet_006 = fillet(
    _edges_at(
        chamfer_0,
        [
            (-14, 17.613914953808536, 5),
            (-14, -17.613914953808536, 5),
            (14, 17.613914953808536, 5),
            (14, -17.613914953808536, 5),
        ],
    ),
    radius=2,
)

# PartDesign::Fillet 'Fillet007': radius=1.5 on 3 edges of Fillet006
fillet_007 = fillet(
    _edges_at(
        fillet_006,
        [(14, -14.810385069297332, 10), (14, 0, 0), (14, 14.810385069297329, 10)],
    ),
    radius=1.5,
)

result = fillet_007
