"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/ISO7091DIN126_CLASS_C_M18FlatWasher.FCStd."""

from build123d import Circle, extrude

# Sketcher::SketchObject 'Sketch': 2 circles (2 loops)
sketch = Circle(17) - Circle(10)

# PartDesign::Pad 'Pad': length=3.0
pad = extrude(sketch, amount=3)

result = pad
