"""Sources: https://amesweb.info, Machinery's Handbook, ASME B18.2.8-1999

Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/M3LooseMean.FCStd.
"""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=1.875, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(1.875, 15)

result = cylinder
