"""Sources: https://amesweb.info, Machinery's Handbook, ASME B18.2.8-1999

Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/M64CloseMax.FCStd.
"""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=33.15, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(33.15, 15)

result = cylinder
