"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_120x80x8_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-24, 52), (24, 52))
    + CenterArc(center=(24, 44), radius=8, start_angle=90, arc_size=-90)
    + Line((32, 44), (32, -44))
    + CenterArc(center=(24, -44), radius=8, start_angle=360, arc_size=-90)
    + Line((24, -52), (-24, -52))
    + CenterArc(center=(-24, -44), radius=8, start_angle=270, arc_size=-90)
    + Line((-32, -44), (-32, 44))
    + CenterArc(center=(-24, 44), radius=8, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-28, 60), (28, 60))
    + CenterArc(center=(28, 48), radius=12, start_angle=90, arc_size=-90)
    + Line((40, 48), (40, -48))
    + CenterArc(center=(28, -48), radius=12, start_angle=360, arc_size=-90)
    + Line((28, -60), (-28, -60))
    + CenterArc(center=(-28, -48), radius=12, start_angle=270, arc_size=-90)
    + Line((-40, -48), (-40, 48))
    + CenterArc(center=(-28, 48), radius=12, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 120x80x8 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_120x80x8_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_120x80x8_en10219_s235jrh
