"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_260x180x12_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-66, 118), (66, 118))
    + CenterArc(center=(66, 106), radius=12, start_angle=90, arc_size=-90)
    + Line((78, 106), (78, -106))
    + CenterArc(center=(66, -106), radius=12, start_angle=360, arc_size=-90)
    + Line((66, -118), (-66, -118))
    + CenterArc(center=(-66, -106), radius=12, start_angle=270, arc_size=-90)
    + Line((-78, -106), (-78, 106))
    + CenterArc(center=(-66, 106), radius=12, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-72, 130), (72, 130))
    + CenterArc(center=(72, 112), radius=18, start_angle=90, arc_size=-90)
    + Line((90, 112), (90, -112))
    + CenterArc(center=(72, -112), radius=18, start_angle=360, arc_size=-90)
    + Line((72, -130), (-72, -130))
    + CenterArc(center=(-72, -112), radius=18, start_angle=270, arc_size=-90)
    + Line((-90, -112), (-90, 112))
    + CenterArc(center=(-72, 112), radius=18, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 260x180x12 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_260x180x12_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_260x180x12_en10219_s235jrh
