"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_200x120x12_5_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-31.5, 87.5), (31.499999999998344, 87.5))
    + CenterArc(center=(31.5, 71.5), radius=16, start_angle=90, arc_size=-90)
    + Line((47.5, 71.5), (47.5, -71.49999999999338))
    + CenterArc(center=(31.5, -71.5), radius=16, start_angle=360, arc_size=-90)
    + Line((31.499999999999996, -87.5), (-31.499999999995044, -87.5))
    + CenterArc(center=(-31.5, -71.5), radius=16, start_angle=270, arc_size=-90)
    + Line((-47.5, -71.5), (-47.5, 71.4999999999967))
    + CenterArc(center=(-31.5, 71.5), radius=16, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-36, 100), (36, 100))
    + CenterArc(center=(36, 76), radius=24, start_angle=90, arc_size=-90)
    + Line((60, 76), (60, -76))
    + CenterArc(center=(36, -76), radius=24, start_angle=360, arc_size=-90)
    + Line((36, -100), (-36, -100))
    + CenterArc(center=(-36, -76), radius=24, start_angle=270, arc_size=-90)
    + Line((-60, -76), (-60, 76))
    + CenterArc(center=(-36, 76), radius=24, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 200x120x12.5 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_200x120x12_5_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_200x120x12_5_en10219_s235jrh
