"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_180x100x5_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-40, 85), (40, 85))
    + CenterArc(center=(40, 80), radius=5, start_angle=90, arc_size=-90)
    + Line((45, 80), (45, -80))
    + CenterArc(center=(40, -80), radius=5, start_angle=360, arc_size=-90)
    + Line((40, -85), (-40, -85))
    + CenterArc(center=(-40, -80), radius=5, start_angle=270, arc_size=-90)
    + Line((-45, -80), (-45, 80))
    + CenterArc(center=(-40, 80), radius=5, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-42.5, 90), (42.49999999999923, 90))
    + CenterArc(center=(42.5, 82.5), radius=7.5, start_angle=90, arc_size=-90)
    + Line((50, 82.5), (50, -82.4999999999969))
    + CenterArc(center=(42.5, -82.5), radius=7.5, start_angle=360, arc_size=-90)
    + Line((42.5, -90), (-42.49999999999767, -90))
    + CenterArc(center=(-42.5, -82.5), radius=7.5, start_angle=270, arc_size=-90)
    + Line((-50, -82.5), (-50, 82.49999999999847))
    + CenterArc(center=(-42.5, 82.5), radius=7.5, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 180x100x5 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_180x100x5_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_180x100x5_en10219_s235jrh
