"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_300x200x6_3_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-87.4, 143.70000000000002), (87.39999999999935, 143.70000000000002))
    + CenterArc(center=(87.4, 137.4), radius=6.3, start_angle=90, arc_size=-90)
    + Line((93.7, 137.4), (93.7, -137.3999999999974))
    + CenterArc(center=(87.4, -137.4), radius=6.3, start_angle=360, arc_size=-90)
    + Line((87.4, -143.70000000000002), (-87.39999999999807, -143.70000000000002))
    + CenterArc(center=(-87.4, -137.4), radius=6.3, start_angle=270, arc_size=-90)
    + Line((-93.7, -137.4), (-93.7, 137.3999999999987))
    + CenterArc(center=(-87.4, 137.4), radius=6.3, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-90.55, 150), (90.549999999999, 150))
    + CenterArc(center=(90.55, 140.55), radius=9.45, start_angle=90, arc_size=-90)
    + Line((100, 140.55), (100, -140.5499999999961))
    + CenterArc(center=(90.55, -140.55), radius=9.45, start_angle=360, arc_size=-90)
    + Line((90.55, -150), (-90.54999999999707, -150))
    + CenterArc(center=(-90.55, -140.55), radius=9.45, start_angle=270, arc_size=-90)
    + Line((-100, -140.55), (-100, 140.54999999999808))
    + CenterArc(center=(-90.55, 140.55), radius=9.45, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 300x200x6.3 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_300x200x6_3_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_300x200x6_3_en10219_s235jrh
