"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_250x150x5_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-65, 120), (65, 120))
    + CenterArc(center=(65, 115), radius=5, start_angle=90, arc_size=-90)
    + Line((70, 115), (70, -115))
    + CenterArc(center=(65, -115), radius=5, start_angle=360, arc_size=-90)
    + Line((65, -120), (-65, -120))
    + CenterArc(center=(-65, -115), radius=5, start_angle=270, arc_size=-90)
    + Line((-70, -115), (-70, 115))
    + CenterArc(center=(-65, 115), radius=5, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-67.5, 125), (67.4999999999992, 125))
    + CenterArc(center=(67.5, 117.5), radius=7.5, start_angle=90, arc_size=-90)
    + Line((75, 117.5), (75, -117.4999999999969))
    + CenterArc(center=(67.5, -117.5), radius=7.5, start_angle=360, arc_size=-90)
    + Line((67.5, -125), (-67.49999999999767, -125))
    + CenterArc(center=(-67.5, -117.5), radius=7.5, start_angle=270, arc_size=-90)
    + Line((-75, -117.5), (-75, 117.49999999999847))
    + CenterArc(center=(-67.5, 117.5), radius=7.5, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 250x150x5 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_250x150x5_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_250x150x5_en10219_s235jrh
