"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_200x120x6_3_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-45.7, 93.7), (45.69999999999918, 93.7))
    + CenterArc(center=(45.7, 85.7), radius=8, start_angle=90, arc_size=-90)
    + Line((53.7, 85.7), (53.7, -85.69999999999668))
    + CenterArc(center=(45.7, -85.7), radius=8, start_angle=360, arc_size=-90)
    + Line((45.7, -93.7), (-45.69999999999753, -93.7))
    + CenterArc(center=(-45.7, -85.7), radius=8, start_angle=270, arc_size=-90)
    + Line((-53.7, -85.7), (-53.7, 85.69999999999835))
    + CenterArc(center=(-45.7, 85.7), radius=8, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-48, 100), (48, 100))
    + CenterArc(center=(48, 88), radius=12, start_angle=90, arc_size=-90)
    + Line((60, 88), (60, -88))
    + CenterArc(center=(48, -88), radius=12, start_angle=360, arc_size=-90)
    + Line((48, -100), (-48, -100))
    + CenterArc(center=(-48, -88), radius=12, start_angle=270, arc_size=-90)
    + Line((-60, -88), (-60, 88))
    + CenterArc(center=(-48, 88), radius=12, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 200x120x6.3 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_200x120x6_3_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_200x120x6_3_en10219_s235jrh
