"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Rectangular_hollow_section_250_x150x6_3_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-62.4, 118.7), (62.399999999999345, 118.7))
    + CenterArc(center=(62.4, 112.4), radius=6.3, start_angle=90, arc_size=-90)
    + Line((68.7, 112.4), (68.7, -112.39999999999739))
    + CenterArc(center=(62.4, -112.4), radius=6.3, start_angle=360, arc_size=-90)
    + Line((62.4, -118.7), (-62.39999999999805, -118.7))
    + CenterArc(center=(-62.4, -112.4), radius=6.3, start_angle=270, arc_size=-90)
    + Line((-68.7, -112.4), (-68.7, 112.3999999999987))
    + CenterArc(center=(-62.4, 112.4), radius=6.3, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-65.55, 125), (65.549999999999, 125))
    + CenterArc(center=(65.55, 115.55), radius=9.45, start_angle=90, arc_size=-90)
    + Line((75, 115.55), (75, -115.5499999999961))
    + CenterArc(center=(65.55, -115.55), radius=9.45, start_angle=360, arc_size=-90)
    + Line((65.55, -125), (-65.54999999999707, -125))
    + CenterArc(center=(-65.55, -115.55), radius=9.45, start_angle=270, arc_size=-90)
    + Line((-75, -115.55), (-75, 115.54999999999804))
    + CenterArc(center=(-65.55, 115.55), radius=9.45, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Rectangular hollow section 250 x150x6.3 EN10219 S235JRH': amount=50.0
rectangular_hollow_section_250_x150x6_3_en10219_s235jrh = extrude(sketch, amount=50)

result = rectangular_hollow_section_250_x150x6_3_en10219_s235jrh
