"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Round_Bar_110_EN10060_S235JR.FCStd."""

from build123d import Circle, extrude

# Sketcher::SketchObject 'Sketch': 1 circle (1 loops)
sketch = Circle(55)

# Part::Extrusion 'Round Bar 110 EN10060 S235JR': amount=50.0
round_bar_110_en10060_s235jr = extrude(sketch, amount=50)

result = round_bar_110_en10060_s235jr
