"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Screw_M12x240_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((5.999, 0), (9, 0), (9, 11.97229))
    + CenterArc(center=(8.97229, 11.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (8.972289999999996, 12),
        (0, 12),
        (0, -240),
        (4.25, -240),
        (6, -238.25),
        (6, -204),
        (5.999, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (5.81391721074, 0),
    (2.906958605371, 5.035000000001),
    (-2.9069586053689997, 5.034999999999),
    (-5.813917210742, 0),
    (-2.9069586053709995, -5.034999999999),
    (2.9069586053689997, -5.034999999999),
    (5.81391721074, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 12), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M12x240 ISO4762 8,8 A2K' (body-less, standalone): length=10.07
screw_m12x240_iso4762_8_8_a2k = extrude(sketch_001, amount=-10.07)

result = screw_m12x240_iso4762_8_8_a2k
