"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Screw_M10x70_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((4.999, 0), (8, 0), (8, 9.97229))
    + CenterArc(center=(7.97229, 9.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (7.972289999999997, 10),
        (0, 10),
        (0, -70),
        (3.5, -70),
        (5, -68.5),
        (5, -38),
        (4.999, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (4.65921667236, 0),
    (2.32960833618, 4.035),
    (-2.32960833618, 4.035),
    (-4.65921667236, 0),
    (-2.32960833618, -4.035),
    (2.32960833618, -4.035),
    (4.65921667236, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 10), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M10x70 ISO4762 8,8 A2K' (body-less, standalone): length=8.07
screw_m10x70_iso4762_8_8_a2k = extrude(sketch_001, amount=-8.07)

result = screw_m10x70_iso4762_8_8_a2k
