"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Screw_M5x140_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((2.499, 0), (4.25, 0), (4.249999999941, 4.97229))
    + CenterArc(
        center=(4.222289999941, 4.97229), radius=0.02771, start_angle=0, arc_size=90
    )
    + Polyline(
        (4.2222899999409975, 5),
        (0, 5),
        (0, -140),
        (1.7, -140),
        (2.5, -139.2),
        (2.5, -118),
        (2.499, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (2.34404209291, 0),
    (1.172021046455, 2.03),
    (-1.172021046455, 2.03),
    (-2.34404209291, 0),
    (-1.172021046455, -2.03),
    (1.172021046455, -2.03),
    (2.34404209291, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 5), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M5x140 ISO4762 8,8 A2K' (body-less, standalone): length=4.06
screw_m5x140_iso4762_8_8_a2k = extrude(sketch_001, amount=-4.06)

result = screw_m5x140_iso4762_8_8_a2k
