"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Screw_M4x110_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((1.999, 0), (3.5, 0), (3.5, 3.97229))
    + CenterArc(center=(3.47229, 3.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (3.4722899999999974, 4),
        (0, 4),
        (0, -110),
        (1.3, -110),
        (2, -109.3),
        (2, -90),
        (1.999, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (1.76669182372, 0),
    (0.883345911858, 1.530000000001),
    (-0.8833459118609999, 1.529999999999),
    (-1.766691823719, 0),
    (-0.883345911859, -1.529999999999),
    (0.883345911859, -1.529999999999),
    (1.76669182372, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 4), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M4x110 ISO4762 8,8 A2K' (body-less, standalone): length=3.06
screw_m4x110_iso4762_8_8_a2k = extrude(sketch_001, amount=-3.06)

result = screw_m4x110_iso4762_8_8_a2k
