"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Screw_M6x40_ISO4762_8_8_A2K.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Plane,
    Polyline,
    Sketch,
    extrude,
    make_face,
    revolve,
)

# Sketcher::SketchObject 'Sketch': 8 lines, 1 arc (1 loops)
sketch_profile = (
    Polyline((2.999, 0), (5, 0), (5, 5.97229))
    + CenterArc(center=(4.97229, 5.97229), radius=0.02771, start_angle=0, arc_size=90)
    + Polyline(
        (4.972289999999997, 6),
        (0, 6),
        (0, -40),
        (2, -40),
        (3, -39),
        (3, -16),
        (2.999, 0),
    )
)
sketch = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
    make_face(sketch_profile)
)

# Part::Revolution 'Revolve': angle=360.0
revolve_0 = revolve(sketch, axis=Axis.Z, revolution_arc=360)

# Sketcher::SketchObject 'Sketch001': 6 lines (1 loops)
sketch_001_profile = Polyline(
    (2.921392362101, 0),
    (1.460696181065, 2.530000000013),
    (-1.46069618104, 2.530000000002),
    (-2.921392362081, 0),
    (-1.460696181041, -2.529999999987),
    (1.4606961810399999, -2.529999999987),
    (2.921392362101, 0),
)
sketch_001 = Sketch() + Plane(origin=(0, 0, 6), x_dir=(1, 0, 0), z_dir=(0, 0, 1)) * (
    make_face(sketch_001_profile)
)

# PartDesign::Pocket 'Screw M6x40 ISO4762 8,8 A2K' (body-less, standalone): length=5.06
screw_m6x40_iso4762_8_8_a2k = extrude(sketch_001, amount=-5.06)

result = screw_m6x40_iso4762_8_8_a2k
