"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Sprocket_ISO606_simplex_8x3_0_z15.FCStd."""

from build123d import (
    Axis,
    CenterArc,
    Circle,
    Plane,
    Polyline,
    Rot,
    Sketch,
    extrude,
    make_face,
    revolve,
)


def _pattern_union(base, *additions):
    """Boolean-union ``base`` with each addition via BuildPart.

    Chained ``+`` on build123d Part objects returns a Compound that does not
    fuse overlapping geometry — so for pattern features whose copies overlap
    (e.g. sprocket teeth meeting at the hub) the resulting volume is wrong.
    Routing through BuildPart.add() invokes OCCT's robust boolean fusion.
    """
    from build123d import BuildPart, add

    with BuildPart() as _bp:
        add(base)
        for s in additions:
            add(s)
    return _bp.part


def make_part(Wt=2.8):
    """Translated parametric design. Defaults match the source values."""
    # Sketcher::SketchObject 'Tooth sketch': 6 lines, 5 arcs (1 loops)
    tooth_sketch_profile = (
        CenterArc(
            center=(-4, 18.81960679716768),
            radius=2.5000000000000004,
            start_angle=281.9993273797422,
            arc_size=78.00067262025783,
        )
        + CenterArc(
            center=(8.700000000000005, 18.81960679716769),
            radius=10.2,
            start_angle=180,
            arc_size=-11.2479932693887,
        )
        + CenterArc(
            center=(0, 0),
            radius=20.85,
            start_angle=93.58594994051616,
            arc_size=-7.171899881032331,
        )
        + CenterArc(
            center=(-8.699999999999994, 18.819606797167687),
            radius=10.2,
            start_angle=11.247993269388674,
            arc_size=-11.247993269388726,
        )
        + CenterArc(
            center=(4, 18.81960679716768),
            radius=2.5000000000000004,
            start_angle=180,
            arc_size=78.00067262025783,
        )
        + Polyline(
            (3.4802494802494848, 16.3742316935856),
            (3.4802494802494848, 0),
            (-3.480249480249477, 0),
            (-3.480249480249477, 16.374231693585603),
        )
    )
    tooth_sketch = Sketch() + Plane(
        origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
    ) * (make_face(tooth_sketch_profile))

    # PartDesign::Pad 'Tooth': length=Wt
    tooth = extrude(tooth_sketch, amount=Wt)

    # Sketcher::SketchObject 'Hub sketch': 1 circle (1 loops)
    hub_sketch = Sketch() + Plane(
        origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
    ) * (Circle(14))

    # Sketcher::SketchObject 'Hole sketch': 1 circle (1 loops)
    hole_sketch = Sketch() + Plane(
        origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, -1, 0)
    ) * (Circle(4))

    # PartDesign::PolarPattern 'Teeth': PolarPattern around (0, 1, 0), step=24.0deg, occurrences=15
    teeth = _pattern_union(
        tooth,
        Rot(Y=24) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=48) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=72) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=96) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=120) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=144) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=168) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=192) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=216) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=240) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=264) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=288) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=312) * extrude(tooth_sketch, amount=Wt),
        Rot(Y=336) * extrude(tooth_sketch, amount=Wt),
    )

    # Sketcher::SketchObject 'Radius': 5 lines, 2 arcs (2 loops)
    sketch_001_loop_0 = CenterArc(
        center=(5.2, 16.977016653792585),
        radius=8,
        start_angle=151.04497562814015,
        arc_size=28.95502437185985,
    ) + Polyline(
        (-2.8, 16.977016653792585), (-2.8, 20.85), (-1.7999999999999998, 20.85)
    )
    sketch_001_loop_1 = Polyline(
        (-1, 20.85), (0, 20.85), (0, 16.977016653792585)
    ) + CenterArc(
        center=(-8, 16.977016653792585),
        radius=8,
        start_angle=0,
        arc_size=28.955024371859842,
    )
    radius = Sketch() + Plane(origin=(0, 0, 0), x_dir=(0, 1, 0), z_dir=(1, 0, 0)) * (
        (make_face(sketch_001_loop_0) + make_face(sketch_001_loop_1))
    )

    # PartDesign::Groove 'Teeth Radius': angle=-360.0 (reversed)
    teeth_radius = teeth - revolve(radius, axis=Axis.Y, revolution_arc=-360)

    # PartDesign::Pad 'Hub': length=13.0
    hub = teeth_radius + extrude(hub_sketch, amount=13)

    # PartDesign::Pocket 'Hole': ThroughAll (midplane)
    hole = hub - extrude(hole_sketch, amount=500000, both=True)

    return hole


result = make_part()
