"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Square_hollow_section_40x40x3_6_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-12.799999999998, 16.400000000001), (12.799999999997627, 16.399999999999))
    + CenterArc(
        center=(12.799999999998, 12.799999999999),
        radius=3.6,
        start_angle=90,
        arc_size=-90,
    )
    + Line(
        (16.399999999998002, 12.799999999999), (16.400000000000002, -12.799999999997512)
    )
    + CenterArc(
        center=(12.8, -12.799999999999), radius=3.6, start_angle=360, arc_size=-90
    )
    + Line((12.8, -16.399999999999), (-12.799999999997883, -16.400000000000002))
    + CenterArc(
        center=(-12.799999999999, -12.8), radius=3.6, start_angle=270, arc_size=-90
    )
    + Line((-16.399999999999, -12.8), (-16.399999999998002, 12.800000000000257))
    + CenterArc(
        center=(-12.799999999998, 12.800000000001),
        radius=3.6,
        start_angle=180,
        arc_size=-90,
    )
)
sketch_loop_1 = (
    Line((-14.6, 20), (14.599999999999442, 20))
    + CenterArc(center=(14.6, 14.6), radius=5.4, start_angle=90, arc_size=-90)
    + Line((20, 14.6), (20, -14.599999999997765))
    + CenterArc(center=(14.6, -14.6), radius=5.4, start_angle=360, arc_size=-90)
    + Line((14.599999999999998, -20), (-14.599999999998328, -20))
    + CenterArc(center=(-14.6, -14.6), radius=5.4, start_angle=270, arc_size=-90)
    + Line((-20, -14.6), (-20, 14.59999999999888))
    + CenterArc(center=(-14.6, 14.6), radius=5.4, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 40x40x3.6 EN10219 S235JRH': amount=50.0
square_hollow_section_40x40x3_6_en10219_s235jrh = extrude(sketch, amount=50)

result = square_hollow_section_40x40x3_6_en10219_s235jrh
