"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Square_hollow_section_100x100x6_3_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-37.4, 43.699999999999996), (37.399999999999345, 43.699999999999996))
    + CenterArc(center=(37.4, 37.4), radius=6.3, start_angle=90, arc_size=-90)
    + Line((43.699999999999996, 37.4), (43.699999999999996, -37.3999999999974))
    + CenterArc(center=(37.4, -37.4), radius=6.3, start_angle=360, arc_size=-90)
    + Line((37.4, -43.699999999999996), (-37.39999999999805, -43.699999999999996))
    + CenterArc(center=(-37.4, -37.4), radius=6.3, start_angle=270, arc_size=-90)
    + Line((-43.699999999999996, -37.4), (-43.699999999999996, 37.399999999998705))
    + CenterArc(center=(-37.4, 37.4), radius=6.3, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-40.55, 50), (40.54999999999902, 50))
    + CenterArc(center=(40.55, 40.55), radius=9.45, start_angle=90, arc_size=-90)
    + Line((50, 40.55), (50, -40.54999999999609))
    + CenterArc(center=(40.55, -40.55), radius=9.45, start_angle=360, arc_size=-90)
    + Line((40.55, -50), (-40.54999999999707, -50))
    + CenterArc(center=(-40.55, -40.55), radius=9.45, start_angle=270, arc_size=-90)
    + Line((-50, -40.55), (-50, 40.54999999999805))
    + CenterArc(center=(-40.55, 40.55), radius=9.45, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 100x100x6.3 EN10219 S235JRH': amount=50.0
square_hollow_section_100x100x6_3_en10219_s235jrh = extrude(sketch, amount=50)

result = square_hollow_section_100x100x6_3_en10219_s235jrh
