"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Square_hollow_section_350x350x8_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-159, 167), (159, 167))
    + CenterArc(center=(159, 159), radius=8, start_angle=90, arc_size=-90)
    + Line((167, 159), (167, -159))
    + CenterArc(center=(159, -159), radius=8, start_angle=360, arc_size=-90)
    + Line((159, -167), (-159, -167))
    + CenterArc(center=(-159, -159), radius=8, start_angle=270, arc_size=-90)
    + Line((-167, -159), (-167, 159))
    + CenterArc(center=(-159, 159), radius=8, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-163, 175), (163, 175))
    + CenterArc(center=(163, 163), radius=12, start_angle=90, arc_size=-90)
    + Line((175, 163), (175, -163))
    + CenterArc(center=(163, -163), radius=12, start_angle=360, arc_size=-90)
    + Line((163, -175), (-163, -175))
    + CenterArc(center=(-163, -163), radius=12, start_angle=270, arc_size=-90)
    + Line((-175, -163), (-175, 163))
    + CenterArc(center=(-163, 163), radius=12, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 350x350x8 EN10219 S235JRH': amount=50.0
square_hollow_section_350x350x8_en10219_s235jrh = extrude(sketch, amount=50)

result = square_hollow_section_350x350x8_en10219_s235jrh
