"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Square_hollow_section_400x400x16_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-168, 184), (168, 184))
    + CenterArc(center=(168, 168), radius=16, start_angle=90, arc_size=-90)
    + Line((184, 168), (184, -168))
    + CenterArc(center=(168, -168), radius=16, start_angle=360, arc_size=-90)
    + Line((168, -184), (-168, -184))
    + CenterArc(center=(-168, -168), radius=16, start_angle=270, arc_size=-90)
    + Line((-184, -168), (-184, 168))
    + CenterArc(center=(-168, 168), radius=16, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-176, 200), (176, 200))
    + CenterArc(center=(176, 176), radius=24, start_angle=90, arc_size=-90)
    + Line((200, 176), (200, -176))
    + CenterArc(center=(176, -176), radius=24, start_angle=360, arc_size=-90)
    + Line((176, -200), (-176, -200))
    + CenterArc(center=(-176, -176), radius=24, start_angle=270, arc_size=-90)
    + Line((-200, -176), (-200, 176))
    + CenterArc(center=(-176, 176), radius=24, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 400x400x16 EN10219 S235JRH': amount=50.0
square_hollow_section_400x400x16_en10219_s235jrh = extrude(sketch, amount=50)

result = square_hollow_section_400x400x16_en10219_s235jrh
