"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Square_hollow_section_200x200x12_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-76, 88), (76, 88))
    + CenterArc(center=(76, 76), radius=12, start_angle=90, arc_size=-90)
    + Line((88, 76), (88, -76))
    + CenterArc(center=(76, -76), radius=12, start_angle=360, arc_size=-90)
    + Line((76, -88), (-76, -88))
    + CenterArc(center=(-76, -76), radius=12, start_angle=270, arc_size=-90)
    + Line((-88, -76), (-88, 76))
    + CenterArc(center=(-76, 76), radius=12, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-82, 100), (82, 100))
    + CenterArc(center=(82, 82), radius=18, start_angle=90, arc_size=-90)
    + Line((100, 82), (100, -82))
    + CenterArc(center=(82, -82), radius=18, start_angle=360, arc_size=-90)
    + Line((82, -100), (-82, -100))
    + CenterArc(center=(-82, -82), radius=18, start_angle=270, arc_size=-90)
    + Line((-100, -82), (-100, 82))
    + CenterArc(center=(-82, 82), radius=18, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 200x200x12 EN10219 S235JRH': amount=50.0
square_hollow_section_200x200x12_en10219_s235jrh = extrude(sketch, amount=50)

result = square_hollow_section_200x200x12_en10219_s235jrh
