"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Square_Bar_50_EN10059_S235JR.FCStd."""

from build123d import Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 4 lines (1 loops)
sketch_profile = Polyline((-25, -25), (25, -25), (25, 25), (-25, 25), (-25, -25))
sketch = make_face(sketch_profile)

# Part::Extrusion 'Square Bar 50 EN10059 S235JR': amount=50.0
square_bar_50_en10059_s235jr = extrude(sketch, amount=50)

result = square_bar_50_en10059_s235jr
