"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/Square_hollow_section_60x60x3_EN10219_S235JRH.FCStd."""

from build123d import CenterArc, Line, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 8 arcs (2 loops)
sketch_loop_0 = (
    Line((-24, 27), (24, 27))
    + CenterArc(center=(24, 24), radius=3, start_angle=90, arc_size=-90)
    + Line((27, 24), (27, -24))
    + CenterArc(center=(24, -24), radius=3, start_angle=360, arc_size=-90)
    + Line((24, -27), (-24, -27))
    + CenterArc(center=(-24, -24), radius=3, start_angle=270, arc_size=-90)
    + Line((-27, -24), (-27, 24))
    + CenterArc(center=(-24, 24), radius=3, start_angle=180, arc_size=-90)
)
sketch_loop_1 = (
    Line((-25.5, 30), (25.49999999999953, 30))
    + CenterArc(center=(25.5, 25.5), radius=4.5, start_angle=90, arc_size=-90)
    + Line((30, 25.5), (30, -25.49999999999814))
    + CenterArc(center=(25.5, -25.5), radius=4.5, start_angle=360, arc_size=-90)
    + Line((25.5, -30), (-25.499999999998607, -30))
    + CenterArc(center=(-25.5, -25.5), radius=4.5, start_angle=270, arc_size=-90)
    + Line((-30, -25.5), (-30, 25.49999999999907))
    + CenterArc(center=(-25.5, 25.5), radius=4.5, start_angle=180, arc_size=-90)
)
sketch = make_face(sketch_loop_1) - make_face(sketch_loop_0)

# Part::Extrusion 'Square hollow section 60x60x3 EN10219 S235JRH': amount=50.0
square_hollow_section_60x60x3_en10219_s235jrh = extrude(sketch, amount=50)

result = square_hollow_section_60x60x3_en10219_s235jrh
