"""Sources: https://amesweb.info, Machinery's Handbook, ASME B18.2.8-1999

Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/U_Number_4LooseMin.FCStd.
"""

from build123d import Cylinder, Pos

# Part::Cylinder 'Cylinder': Radius=1.8287999999999998, Height=15.0
cylinder = Pos(0, 0, 5) * Cylinder(1.8287999999999998, 15)

result = cylinder
