"""Auto-generated by fcstd2b123d from tests/fixtures/sample_2026/UPE-Profile_120_DIN1026-2_S235JR.FCStd."""

from build123d import CenterArc, Line, Polyline, extrude, make_face

# Sketcher::SketchObject 'Sketch': 8 lines, 2 arcs (1 loops)
sketch_profile = (
    Line((5, -40), (5, 40))
    + CenterArc(center=(17, 40), radius=12, start_angle=180, arc_size=-90)
    + Polyline(
        (17, 52), (60, 52), (60, 60), (0, 60), (0, -60), (60, -60), (60, -52), (17, -52)
    )
    + CenterArc(center=(17, -40), radius=12, start_angle=270, arc_size=-90)
)
sketch = make_face(sketch_profile)

# Part::Extrusion 'UPE-Profile 120 DIN1026-2 S235JR': amount=50.0
upe_profile_120_din1026_2_s235jr = extrude(sketch, amount=50)

result = upe_profile_120_din1026_2_s235jr
